### ISSUE TITLE
Detected Empty Translation Rows, But No Empty Rows Found in the File

### ISSUE THREAD

**Issue by Yanxueyu** [Huanshere/VideoLingo#110]
I encountered an issue while using the VideoLingo tool, where the following error is thrown:

Detected empty translation rows! Please manually check the following rows in `output\log\translation_results_for_subtitles.xlsx` and fill them with appropriate content, then run again:
[19]
ValueError: Empty translation rows detected

Steps Taken:
I checked the translation_results_for_subtitles.xlsx file, especially row 19 (as mentioned in the error message), but found no empty or missing translations.
I confirmed this by programmatically checking for any empty or whitespace-only rows in the "Translation" column, but none were found.
I tried rerunning the tool after this verification, but the same error persisted.

Observations:
The file does not contain any empty rows in the "Translation" column.
The error still occurs even though the file appears to be correct.

Expected Behavior:
The tool should not raise an error if there are no empty translation rows in the file. It seems the issue may be caused by how the tool is interpreting the translation rows or some other underlying issue in the data validation process.

Could you please investigate this further or suggest any additional steps I might try to resolve the issue?

Errors Content:
Detected empty translation rows! Please manually check the following rows in output\log                          │
│ ranslation_results_for_subtitles.xlsx and fill them with appropriate content, then run again:                       │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
[19]
2024-10-05 04:59:33.749 Uncaught app exception
Traceback (most recent call last):
  File "D:\Work\AI\VideoLingo_v1.4\VideoLingo_v1.4\runtime\Lib\site-packages\streamlit\runtime\scriptrunner\exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "D:\Work\AI\VideoLingo_v1.4\VideoLingo_v1.4\runtime\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 590, in code_to_exec
    exec(code, module.__dict__)
  File "D:\Work\AI\VideoLingo_v1.4\VideoLingo_v1.4\st.py", line 125, in <module>
    main()
  File "D:\Work\AI\VideoLingo_v1.4\VideoLingo_v1.4\st.py", line 121, in main
    text_processing_section()
  File "D:\Work\AI\VideoLingo_v1.4\VideoLingo_v1.4\st.py", line 28, in text_processing_section
    process_text()
  File "D:\Work\AI\VideoLingo_v1.4\VideoLingo_v1.4\st.py", line 62, in process_text
    step6_generate_final_timeline.align_timestamp_main()
  File "D:\Work\AI\VideoLingo_v1.4\VideoLingo_v1.4\core\step6_generate_final_timeline.py", line 136, in align_timestamp_main
    raise ValueError("Empty translation rows detected")
ValueError: Empty translation rows detected

**Comment by Huanshere** [comment]
这个很可能是由于使用了非sonnet模型，在翻译的时候喜欢把不重要的词省略导致的空行翻译，建议使用Claude3.5sonnet。

**Comment by Huanshere** [comment]
在 632f69a 中精简了提示词，并且在 3df4fd6 中更新了文档，现在不建议使用非sonnet的其他模型~
