### ISSUE TITLE
更新后无法导入get_config_value.

### ISSUE THREAD

**Issue by DreamLoveBetty** [Huanshere/VideoLingo#119]
前面运行都是正常的，唯一的操作就是执行了get pull,以下是终端信息
-------------------------------------------------------------------------------------------------------
2024-10-07 03:16:28.314 Uncaught app exception
Traceback (most recent call last):
  File "C:\tools\Miniconda3\envs\videolingo\lib\site-packages\streamlit\runtime\scriptrunner\exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
  File "C:\tools\Miniconda3\envs\videolingo\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 590, in code_to_exec
    exec(code, module.__dict__)
  File "D:\Program\VideoLingo\VideoLingo\st.py", line 3, in <module>
    from st_components.imports_and_utils import *
  File "D:\Program\VideoLingo\VideoLingo\st_components\imports_and_utils.py", line 3, in <module>
    from core import step2_whisper, step1_ytdlp, step3_1_spacy_split, step3_2_splitbymeaning
  File "D:\Program\VideoLingo\VideoLingo\core\step3_2_splitbymeaning.py", line 5, in <module>
    from core.prompts_storage import get_split_prompt
  File "D:\Program\VideoLingo\VideoLingo\core\prompts_storage.py", line 4, in <module>
    from config import get_config_value
ImportError: cannot import name 'get_config_value' from 'config' (D:\Program\VideoLingo\VideoLingo\config.py)

**Comment by DreamLoveBetty** [comment]
问题已经解决，该问题可以关闭.重新用备份的config文件覆盖配置好的config文件就能进入主页面，不过就是要重新设置下API等.

**Comment by yxc0915** [comment]
> 问题已经解决，该问题可以关闭.重新用备份的config文件覆盖配置好的config文件就能进入主页面，不过就是要重新设置下API等.

麻烦你那边关闭一下😉，在你右下角的位置有个紫色的关闭按钮

**Comment by Huanshere** [comment]
哈哈哈哈昨晚偷偷更新了一下代码，你的安装刚好在那个时间点😉
