### ISSUE TITLE
get_prompt_expressiveness     for key, value in faithfulness_result.items():

### ISSUE THREAD

**Issue by pq784844602** [Huanshere/VideoLingo#12]
2024-08-23 18:26:11.501 Uncaught app exception
Traceback (most recent call last):
  File "D:\data\miniconda3\envs\videolingo\Lib\site-packages\streamlit\runtime\scriptrunner\exec_code.py", line 85, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "D:\data\miniconda3\envs\videolingo\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 576, in code_to_exec
    exec(code, module.__dict__)
  File "D:\www\VideoLingo\st.py", line 242, in <module>
    main()
  File "D:\www\VideoLingo\st.py", line 238, in main
    if text_processing_section(progress_bar, step_status, total_steps):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\www\VideoLingo\st.py", line 128, in text_processing_section
    process_text(progress_bar, step_status, total_steps)
  File "D:\www\VideoLingo\st.py", line 178, in process_text
    func()
  File "D:\www\VideoLingo\st.py", line 171, in <lambda>
    ("总结和翻译...", lambda: (step4_1_summarize.get_summary(), step4_2_translate_all.translate_all()), 4),
                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\www\VideoLingo\core\step4_2_translate_all.py", line 61, in translate_all
    results.append(future.result())
                   ^^^^^^^^^^^^^^^
  File "D:\data\miniconda3\envs\videolingo\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "D:\data\miniconda3\envs\videolingo\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "D:\data\miniconda3\envs\videolingo\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\www\VideoLingo\core\step4_2_translate_all.py", line 39, in translate_chunk
    translation, english_result = translate_lines(chunk, previous_content_prompt, after_content_prompt, things_to_note_prompt, theme_prompt, i)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\www\VideoLingo\core\step4_2_translate_once.py", line 21, in translate_lines
    prompt2 = get_prompt_expressiveness(faith_result, lines, shared_prompt,target_language=TARGET_LANGUAGE)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\www\VideoLingo\core\prompts_storage.py", line 185, in get_prompt_expressiveness
    for key, value in faithfulness_result.items():
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'items'

**Comment by pq784844602** [comment]
![image](https://github.com/user-attachments/assets/e5b127ba-6d35-4402-bcec-060356169f49)

**Comment by Huanshere** [comment]
能够提供 output/gpt_log/faithxxx.json 中的最后几个记录查看问题
