### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './_model_cache\\uvr5_weights\\HP2_all_vocals.pth'

### ISSUE THREAD

**Issue by hongyuhei7722** [Huanshere/VideoLingo#124]
源码安装后，下载youtube链接成功（8分钟：https://www.youtube.com/watch?v=5RALFlyfmKM）
开始处理字幕，显示：
 Starting UVR5 processing                                                                                             │
│ Device: cuda                                                                                                         │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Processing segment 0: segment_0_480.wav                                                                              │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
Starting vocal separation...
2024-10-07 17:20:03.573 Uncaught app exception
Traceback (most recent call last):
  File "D:\anaconda3\envs\videolingo\lib\site-packages\streamlit\runtime\scriptrunner\exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
  File "D:\anaconda3\envs\videolingo\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 590, in code_to_exec
    exec(code, module.__dict__)
  File "D:\download\VideoLingo\st.py", line 124, in <module>
    main()
  File "D:\download\VideoLingo\st.py", line 120, in main
    text_processing_section()
  File "D:\download\VideoLingo\st.py", line 36, in text_processing_section
    process_text()
  File "D:\download\VideoLingo\st.py", line 51, in process_text
    step2_whisper.transcribe()
  File "D:\download\VideoLingo\core\step2_whisper.py", line 23, in transcribe
    ts(video_file)
  File "D:\download\VideoLingo\core\all_whisper_methods\whisperX.py", line 114, in transcribe
    uvr5_for_videolingo(
  File "D:\download\VideoLingo\third_party\uvr5\uvr5_for_videolingo.py", line 66, in uvr5_for_videolingo
    process_segment(segment_file, save_dir, device, MODEL_DIR, segment_count)
  File "D:\download\VideoLingo\third_party\uvr5\uvr5_for_videolingo.py", line 19, in process_segment
    ap = AudioPre(agg=10, model_path=os.path.join(model_dir, "uvr5_weights", "HP2_all_vocals.pth"), device=device, is_half=False)
  File "D:\download\VideoLingo\third_party\uvr5\vr.py", line 33, in __init__
    cpk = torch.load(model_path, map_location="cpu")
  File "D:\anaconda3\envs\videolingo\lib\site-packages\torch\serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "D:\anaconda3\envs\videolingo\lib\site-packages\torch\serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "D:\anaconda3\envs\videolingo\lib\site-packages\torch\serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './_model_cache\\uvr5_weights\\HP2_all_vocals.pth'
——请帮忙分析

**Comment by Huanshere** [comment]
这个模型会在python install.py的最后下载，请重新执行并检查下载是否出错~ 保持网络与huggingface畅通

**Comment by colin4k** [comment]
> 这个模型会在python install.py的最后下载，请重新执行并检查下载是否出错~ 保持网络与huggingface畅通

考虑国内网络的环境，建议增加选择使用 hf-mirror 镜像下载的功能

**Comment by wangaocheng** [comment]
是的，你的模型没有下载。

**Comment by Huanshere** [comment]
网络环境问题暂时没有精力解决，如果有想法可以提 PR，代码在 install.py 中～

**Comment by rockets-cn** [comment]
def dowanload_uvr_model():
        """Download the specified uvr models."""
        models = {
            "HP2_all_vocals.pth": "https://huggingface.co/lj1995/VoiceConversionWebUI/resolve/e992cb1bc5d777fcddce20735a899219b1d46aba/uvr5_weights/HP2_all_vocals.pth",
            "VR-DeEchoAggressive.pth": "https://huggingface.co/lj1995/VoiceConversionWebUI/resolve/main/uvr5_weights/VR-DeEchoAggressive.pth"
        }
采用该代码解决，供以上朋友参考。

**Comment by Huanshere** [comment]
肥肠感谢！待会我合并进来！

**Comment by yxc0915** [comment]
> 在install.py文件中，找到如下语句，将 原huggingface的网址改为hf-mirror.com即可，可以直接复制黏贴该代码替代这部分内容。
> 
> ```
>  def dowanload_uvr_model():
>         """Download the specified uvr models."""
>         models = {
>             "HP2_all_vocals.pth": "https://hf-mirror.com/lj1995/VoiceConversionWebUI/resolve/e992cb1bc5d777fcddce20735a899219b1d46aba/uvr5_weights/HP2_all_vocals.pth",
>             "VR-DeEchoAggressive.pth": "https://hf-mirror.com/lj1995/VoiceConversionWebUI/resolve/main/uvr5_weights/VR-DeEchoAggressive.pth"
>         }
> ```
> 
> 采用该代码解决，供以上朋友参考。

已提交PR以实现官方和HF镜像的自动选择，感谢你的反馈

**Comment by yxc0915** [comment]
@Huanshere 把这issues关了吧
