### ISSUE TITLE
处理字幕的时候报错，log如下

### ISSUE THREAD

**Issue by tomridder** [Huanshere/VideoLingo#156]
━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Language    ┃ Parts                                     ┃
┡━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ SRC_LANG    │ HIS RANT YESTERDAY OR TODAY ON TWITTER    │
│             │  DID MORE THAN EVERY CABLE NEWS MONOLOGUE │
│ TARGET_LANG │ 他昨天或今天在推特上的 rant               │
│             │ 比所有有线新闻的独白更有影响。            │
└─────────────┴───────────────────────────────────────────┘
✅ Subtitles splitting completed!
╭──────────────────────────────────────────────────────────────────────────────╮
│ 🚫 Detected empty translation rows! Please manually check the following rows │
│ in `output\log     ranslation_results_for_subtitles.xlsx` and fill them with │
│ appropriate content, then run again:                                         │
╰──────────────────────────────────────────────────────────────────────────────╯
[121, 429, 535]
2024-10-15 21:08:38.460 Uncaught app exception
Traceback (most recent call last):
  File "/opt/anaconda3/envs/videolingo/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
  File "/opt/anaconda3/envs/videolingo/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 590, in code_to_exec
    exec(code, module.__dict__)
  File "/Users/guichaoran/VideoLingo/st.py", line 128, in <module>
    main()
  File "/Users/guichaoran/VideoLingo/st.py", line 124, in main
    text_processing_section()
  File "/Users/guichaoran/VideoLingo/st.py", line 35, in text_processing_section
    process_text()
  File "/Users/guichaoran/VideoLingo/st.py", line 65, in process_text
    step6_generate_final_timeline.align_timestamp_main()
  File "/Users/guichaoran/VideoLingo/core/step6_generate_final_timeline.py", line 129, in align_timestamp_main
    raise ValueError("Empty translation rows detected")
ValueError: Empty translation rows detected

**Comment by Huanshere** [comment]
349c374 不再检测空行，即允许翻译片段出现空行，很多时候是因为合并到了上一句
