### ISSUE TITLE
偶尔报错The message you submitted was too long, please reload the conversation and submit something shorter.

### ISSUE THREAD

**Issue by tomridder** [Huanshere/VideoLingo#159]
└──────────┴───────────────────────────────────────────────────────────────────┘
✅ All sentences have been successfully split!
📝 Summarizing... Please wait a moment...
Unexpected error occurred: Error code: 400 - {'error': {'message': 'The message you submitted was too long, please reload the conversation and submit something shorter. (request id: 20241016090948437769917NidT1rzM)', 'type': 'invalid_request_error', 'param': '', 'code': 'message_length_exceeds_limit'}}
Retrying...
Unexpected error occurred: Error code: 400 - {'error': {'message': 'The message you submitted was too long, please reload the conversation and submit something shorter. (request id: 202410160909512288596767nRwNkpb)', 'type': 'invalid_request_error', 'param': '', 'code': 'message_length_exceeds_limit'}}
Retrying...
2024-10-16 09:09:54.537 Uncaught app exception
Traceback (most recent call last):
  File "/Users/guichaoran/Downloads/Code/VideoLingo/core/ask_gpt.py", line 66, in ask_gpt
    response = client.chat.completions.create(
  File "/opt/anaconda3/envs/videolingo/lib/python3.10/site-packages/openai/_utils/_utils.py", line 274, in wrapper
    return func(*args, **kwargs)
  File "/opt/anaconda3/envs/videolingo/lib/python3.10/site-packages/openai/resources/chat/completions.py", line 704, in create
    return self._post(
  File "/opt/anaconda3/envs/videolingo/lib/python3.10/site-packages/openai/_base_client.py", line 1268, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/opt/anaconda3/envs/videolingo/lib/python3.10/site-packages/openai/_base_client.py", line 945, in request
    return self._request(
  File "/opt/anaconda3/envs/videolingo/lib/python3.10/site-packages/openai/_base_client.py", line 1049, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'error': {'message': 'The message you submitted was too long, please reload the conversation and submit something shorter. (request id: 2024101609095471640312vzshfIJM)', 'type': 'invalid_request_error', 'param': '', 'code': 'message_length_exceeds_limit'}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/videolingo/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
  File "/opt/anaconda3/envs/videolingo/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 590, in code_to_exec
    exec(code, module.__dict__)
  File "/Users/guichaoran/Downloads/Code/VideoLingo/st.py", line 118, in <module>
    main()
  File "/Users/guichaoran/Downloads/Code/VideoLingo/st.py", line 114, in main
    text_processing_section()
  File "/Users/guichaoran/Downloads/Code/VideoLingo/st.py", line 30, in text_processing_section
    process_text()
  File "/Users/guichaoran/Downloads/Code/VideoLingo/st.py", line 50, in process_text
    step4_1_summarize.get_summary()
  File "/Users/guichaoran/Downloads/Code/VideoLingo/core/step4_1_summarize.py", line 39, in get_summary
    summary = ask_gpt(summary_prompt, response_json=True, valid_def=valid_summary, log_title='summary')
  File "/Users/guichaoran/Downloads/Code/VideoLingo/core/ask_gpt.py", line 103, in ask_gpt
    raise Exception(f"Still failed after {max_retries} attempts: {e}")
Exception: Still failed after 3 attempts: Error code: 400 - {'error': {'message': 'The message you submitted was too long, please reload the conversation and submit something shorter. (request id: 2024101609095471640312vzshfIJM)', 'type': 'invalid_request_error', 'param': '', 'code': 'message_length_exceeds_limit'}}

**Comment by Huanshere** [comment]
1a96817 已修复，仅仅使用前 4k 字符进行总结
