### ISSUE TITLE
偶现报错 ValueError: All arrays must be of the same length

### ISSUE THREAD

**Issue by tomridder** [Huanshere/VideoLingo#161]
2024-10-17 00:10:56.729 Uncaught app exception
Traceback (most recent call last):
  File "/opt/anaconda3/envs/videolingo/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
  File "/opt/anaconda3/envs/videolingo/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 590, in code_to_exec
    exec(code, module.__dict__)
  File "/Users/guichaoran/Downloads/Code/VideoLingo/st.py", line 118, in <module>
    main()
  File "/Users/guichaoran/Downloads/Code/VideoLingo/st.py", line 114, in main
    text_processing_section()
  File "/Users/guichaoran/Downloads/Code/VideoLingo/st.py", line 30, in text_processing_section
    process_text()
  File "/Users/guichaoran/Downloads/Code/VideoLingo/st.py", line 55, in process_text
    step5_splitforsub.split_for_sub_main()
  File "/Users/guichaoran/Downloads/Code/VideoLingo/core/step5_splitforsub.py", line 106, in split_for_sub_main
    pd.DataFrame({'Source': src_lines, 'Translation': tr_lines}).to_excel("output/log/translation_results_for_subtitles.xlsx", index=False)
  File "/opt/anaconda3/envs/videolingo/lib/python3.10/site-packages/pandas/core/frame.py", line 778, in __init__
    mgr = dict_to_mgr(data, index, columns, dtype=dtype, copy=copy, typ=manager)
  File "/opt/anaconda3/envs/videolingo/lib/python3.10/site-packages/pandas/core/internals/construction.py", line 503, in dict_to_mgr
    return arrays_to_mgr(arrays, columns, index, dtype=dtype, typ=typ, consolidate=copy)
  File "/opt/anaconda3/envs/videolingo/lib/python3.10/site-packages/pandas/core/internals/construction.py", line 114, in arrays_to_mgr
    index = _extract_index(arrays)
  File "/opt/anaconda3/envs/videolingo/lib/python3.10/site-packages/pandas/core/internals/construction.py", line 677, in _extract_index
    raise ValueError("All arrays must be of the same length")
ValueError: All arrays must be of the same length

**Comment by cn0xroot** [comment]
> 请问使用的什么大模型，是否保存了日志

用gpt-3.5-turbo 有时候也会碰到这个报错 导致程序终止

**Comment by Huanshere** [comment]
建议使用 claude3.5sonnet，弱模型容易报错，具体原因在文档里写清楚了～
