### ISSUE TITLE
Docker build 报错

### ISSUE THREAD

**Issue by cn0xroot** [Huanshere/VideoLingo#162]
```
 => transferring context: 2B                                                                                                        0.0s
 => [ 1/14] FROM docker.io/nvidia/cuda:12.4.1-devel-ubuntu20.04@sha256:8d577fd078ae56c37493af4454a5b700c72a7f1aeb9ff3d0adc0459fc477  158.9s
 => => resolve docker.io/nvidia/cuda:12.4.1-devel-ubuntu20.04@sha256:8d577fd078ae56c37493af4454a5b700c72a7f1aeb9ff3d0adc0459fc47752a4  0.0s
 => => sha256:b59685b95b83b5d1b7065d103bc4ff1b0c56b7ead0e979963b9a28dfc43f25f9 17.76kB / 17.76kB                                       0.0s
 => => sha256:fb67143098b346a05ff35775af9ba34ccf9a89e4079f4ceb9a51b05ae257e78c 25.97MB / 25.97MB                                       2.1s
 => => sha256:8d577fd078ae56c37493af4454a5b700c72a7f1aeb9ff3d0adc0459fc47752a4 743B / 743B                                             0.0s
 => => sha256:200bf1dc4e277c12901318351379d3c7ac7a72df1d4de7b42138d48c0774893c 2.63kB / 2.63kB                                         0.0s
 => => sha256:9191513e3982ddf6beab44bbf59482e7169639ba303f3a266cfffff65eb0b0dc 7.79MB / 7.79MB                                         2.5s
 => => sha256:f0acf1e33b025c846f726d56bfb16e472c057e6d9a36e75e617facf49b8c79c0 380.06kB / 380.06kB                                     1.2s
 => => sha256:1f06fa69061963e2fd5dd2ce8bec4a178ece52bd57d8c5f748239a13742face7 187B / 187B                                             1.5s
 => => sha256:56dc8550293751a1604e97ac949cfae82ba20cb2a28e034737bafd7382559609 6.89kB / 6.89kB                                         2.1s
 => => extracting sha256:fb67143098b346a05ff35775af9ba34ccf9a89e4079f4ceb9a51b05ae257e78c                                              0.6s
 => => sha256:63cc2bf5139037d235709eb9c5c52ad6e01778ab9ab3de425847c4427c919284 1.37GB / 1.37GB                                       107.7s
 => => sha256:8447986850389132577ea338a9199658dd161ca862b4a5934de6e6a1142d935f 62.24kB / 62.24kB                                       2.9s
 => => sha256:7e4e3072c3970dbc2a412021fbfe6b09993fc82edc29d4575e9a566a942ad299 1.69kB / 1.69kB                                         4.0s
 => => extracting sha256:9191513e3982ddf6beab44bbf59482e7169639ba303f3a266cfffff65eb0b0dc                                              0.2s
 => => sha256:884865955ae807bfb999bd442953845c8c15e60e0f1db34a969174719941b5cf 1.52kB / 1.52kB                                         3.4s
 => => extracting sha256:f0acf1e33b025c846f726d56bfb16e472c057e6d9a36e75e617facf49b8c79c0                                              0.0s
 => => extracting sha256:1f06fa69061963e2fd5dd2ce8bec4a178ece52bd57d8c5f748239a13742face7                                              0.0s
 => => extracting sha256:56dc8550293751a1604e97ac949cfae82ba20cb2a28e034737bafd7382559609                                              0.0s
 => => sha256:5bdb79321deb97669ad72f3655eb0cb1e2a122cf77e9b7f48d945151a0ee17d5 2.15GB / 2.15GB                                       141.8s
 => => sha256:9b131288cb72ff5acecad7993cbe374db170f72fb0e1aa8b89a49857e66cab26 85.53kB / 85.53kB                                       5.9s
 => => extracting sha256:63cc2bf5139037d235709eb9c5c52ad6e01778ab9ab3de425847c4427c919284                                              9.7s
 => => extracting sha256:8447986850389132577ea338a9199658dd161ca862b4a5934de6e6a1142d935f                                              0.0s
 => => extracting sha256:7e4e3072c3970dbc2a412021fbfe6b09993fc82edc29d4575e9a566a942ad299                                              0.0s
 => => extracting sha256:884865955ae807bfb999bd442953845c8c15e60e0f1db34a969174719941b5cf                                              0.0s
 => => extracting sha256:5bdb79321deb97669ad72f3655eb0cb1e2a122cf77e9b7f48d945151a0ee17d5                                             17.0s
 => => extracting sha256:9b131288cb72ff5acecad7993cbe374db170f72fb0e1aa8b89a49857e66cab26                                              0.0s
 => [internal] load build context                                                                                                      0.0s
 => => transferring context: 354B                                                                                                      0.0s
 => [ 2/14] RUN sed -i 's/archive.ubuntu.com/mirrors.aliyun.com/g' /etc/apt/sources.list &&     sed -i 's/security.ubuntu.com/mirro  104.0s
 => [ 3/14] RUN apt-get clean && rm -rf /var/lib/apt/lists/*                                                                           0.1s
 => [ 4/14] RUN ldconfig /usr/local/cuda-$(echo 12.4.1 | cut -d. -f1,2)/compat/                                                        0.1s
 => [ 5/14] WORKDIR /app                                                                                                               0.0s
 => [ 6/14] RUN git clone https://github.com/Huanshere/VideoLingo.git .                                                                1.9s
 => [ 7/14] RUN pip install torch==2.0.0 torchaudio==2.0.0 --index-url https://download.pytorch.org/whl/cu118                         21.0s
 => [ 8/14] RUN rm -rf .git                                                                                                            0.1s
 => [ 9/14] RUN pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple &&     pip install --no-cache-dir --upgrade   5.1s
 => [10/14] RUN cd third_party/whisperX && pip install --no-cache-dir -e .                                                            82.1s
 => [11/14] COPY requirements.txt .                                                                                                    0.0s
 => [12/14] RUN pip install --no-cache-dir -r requirements.txt                                                                       469.0s
 => [13/14] RUN mkdir -p _model_cache/uvr5_weights &&     wget -O _model_cache/uvr5_weights/HP2_all_vocals.pth https://huggingface.co  7.1s
 => ERROR [14/14] RUN python3 -c "from core.config_utils import update_key; update_key('display_language', 'en_US')"                   0.1s
------
 > [14/14] RUN python3 -c "from core.config_utils import update_key; update_key('display_language', 'en_US')":
0.119 Traceback (most recent call last):
0.119   File "<string>", line 1, in <module>
0.119   File "/app/core/config_utils.py", line 47, in update_key
0.119     raise KeyError(f"Key '{keys[-1]}' not found in configuration")
0.119 KeyError: "Key 'display_language' not found in configuration"
------
Dockerfile:53
--------------------
  51 |
  52 |     # Set language
  53 | >>> RUN python3 -c "from core.config_utils import update_key; update_key('display_language', 'en_US')"
  54 |
  55 |     # Set CUDA-related environment variables
--------------------
ERROR: failed to solve: process "/bin/sh -c python3 -c \"from core.config_utils import update_key; update_key('display_language', 'en_US')\"" did not complete successfully: exit code: 1

View build details: docker-desktop://dashboard/build/desktop-linux/desktop-linux/j6nhmtix80rivpgsuddmldtal
```

测试环境：Mac 14.6.1   Ubuntu 22.04

同样的报错

是需要修改系统语言吗

**Comment by Huanshere** [comment]
sorry 这是之前重构多语言支持文件遗留的bug， 在 335816d 中修复了！感谢！
