### ISSUE TITLE
音频处理频繁出错：Audio buffer is not finite everywher

### ISSUE THREAD

**Issue by cn0xroot** [Huanshere/VideoLingo#166]
```
╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Starting UVR5 processing                                                                                                                 │
│ Device: mps                                                                                                                              │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Processing segment 0: segment_0_600.wav                                                                                                  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
Starting vocal separation...
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 216/216 [00:47<00:00,  4.52it/s]
2024-10-17 20:56:34.336 Uncaught app exception
Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/envs/videolingo/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
  File "/opt/homebrew/anaconda3/envs/videolingo/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 590, in code_to_exec
    exec(code, module.__dict__)
  File "/Users/AI_Project/VideoLingo/st.py", line 118, in <module>
    main()
  File "/Users/AI_Project/VideoLingo/st.py", line 114, in main
    text_processing_section()
  File "/Users/AI_Project/VideoLingo/st.py", line 30, in text_processing_section
    process_text()
  File "/Users/AI_Project/VideoLingo/st.py", line 45, in process_text
    step2_whisper.transcribe()
  File "/Users/AI_Project/VideoLingo/core/step2_whisper.py", line 23, in transcribe
    ts(video_file)
  File "/Users/AI_Project/VideoLingo/core/all_whisper_methods/whisperX.py", line 114, in transcribe
    uvr5_for_videolingo(
  File "/Users/AI_Project/VideoLingo/third_party/uvr5/uvr5_for_videolingo.py", line 71, in uvr5_for_videolingo
    process_segment(segment_file, save_dir, device, MODEL_DIR, segment_count)
  File "/Users/AI_Project/VideoLingo/third_party/uvr5/uvr5_for_videolingo.py", line 20, in process_segment
    ap._path_audio_(segment_file, save_dir, save_dir, format='wav')
  File "/Users/AI_Project/VideoLingo/third_party/uvr5/vr.py", line 122, in _path_audio_
    wav_instrument = spec_utils.cmb_spectrogram_to_wave(
  File "/Users/AI_Project/VideoLingo/third_party/uvr5/lib/lib_v5/spec_utils.py", line 426, in cmb_spectrogram_to_wave
    wave = librosa.core.resample(wave2, orig_sr=bp["sr"], target_sr=sr, res_type="scipy")
  File "/opt/homebrew/anaconda3/envs/videolingo/lib/python3.10/site-packages/librosa/core/audio.py", line 628, in resample
    util.valid_audio(y, mono=False)
  File "/opt/homebrew/anaconda3/envs/videolingo/lib/python3.10/site-packages/librosa/util/utils.py", line 314, in valid_audio
    raise ParameterError("Audio buffer is not finite everywhere")
librosa.util.exceptions.ParameterError: Audio buffer is not finite everywhere
```

**Comment by Huanshere** [comment]
可能是 librosa 版本问题或者内存不足的问题，我的 mac m1pro 无法复现，你能尝试自己修复吗～

**Comment by cn0xroot** [comment]
64G内存应该够用吧？

M1 Max

**Comment by Huanshere** [comment]
嗯那应该是 librosa 版本，或者兼容性问题

**Comment by Huanshere** [comment]
已修复
