### ISSUE TITLE
1.6.2整合包报错（只处理声音转录和输出srt，未配置配音TTS）

### ISSUE THREAD

**Issue by fuyubi** [Huanshere/VideoLingo#170]
Origin:  
│ Direct: 
│ Free:  
上方字幕润色处理后报错 ↓  之前1.4整合包使用正常
按照提示删除output后重试也不行。

⚠️ Warning: No match found for sentence: bark  bark  bark  bark  bark  bark  bark  bark  bark  bark
Original: 'bark  bark  bark  bark  bark  bark  bark  bark  bark  bark'
Matched: bark bark bark bark all
Similarity: 0.42
──────────────────────────────────────────────────
2024-10-18 17:58:23.243 Uncaught app exception
Traceback (most recent call last):
  File "G:\VideoLingo_v1.6.2\runtime\Lib\site-packages\streamlit\runtime\scriptrunner\exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "G:\VideoLingo_v1.6.2\runtime\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 590, in code_to_exec
    exec(code, module.__dict__)
  File "G:\VideoLingo_v1.6.2\st.py", line 124, in <module>
    main()
  File "G:\VideoLingo_v1.6.2\st.py", line 120, in main
    text_processing_section()
  File "G:\VideoLingo_v1.6.2\st.py", line 36, in text_processing_section
    process_text()
  File "G:\VideoLingo_v1.6.2\st.py", line 59, in process_text
    step4_2_translate_all.translate_all()
  File "G:\VideoLingo_v1.6.2\core\step4_2_translate_all.py", line 98, in translate_all
    df_time = align_timestamp(df_text, df_translate, subtitle_output_configs, output_dir=None, for_display=False)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\VideoLingo_v1.6.2\core\step6_generate_final_timeline.py", line 89, in align_timestamp
    time_stamp_list = get_sentence_timestamps(df_text, df_translate)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\VideoLingo_v1.6.2\core\step6_generate_final_timeline.py", line 73, in get_sentence_timestamps
    raise ValueError("❎ No match found for sentence. Please delete the 'output' directory and rerun the process, ensuring UVR is activated before transcription.")
ValueError: ❎ No match found for sentence. Please delete the 'output' directory and rerun the process, ensuring UVR is activated before transcription.

**Comment by Huanshere** [comment]
请问是否进行了 UVR人声分离

**Comment by fuyubi** [comment]
> 请问是否进行了 UVR人声分离

换成1.6.2整合包后LLM和WhisperX 也是设置好测试了没问题的。下面的配音设置没弄因为不需要，之前1.4整合包是正常跑完任务的，但1.6.2就 一直失败。每次都是翻译完了后报错

**Comment by Huanshere** [comment]
应该是视频的原因，这个原因在于整合包没有进行人声分离，在处理有背景声的视频的时候会对字幕产生影响，导致后续对齐有问题。可以尝试本地安装
