### ISSUE TITLE
个别视频偶现报错 

### ISSUE THREAD

**Issue by tomridder** [Huanshere/VideoLingo#172]
2024-10-21 23:53:26.674 Uncaught app exception
Traceback (most recent call last):
  File "/opt/anaconda3/envs/videolingo/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
  File "/opt/anaconda3/envs/videolingo/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 590, in code_to_exec
    exec(code, module.__dict__)
  File "/Users/guichaoran/Downloads/Code/VideoLingo/st.py", line 118, in <module>
    main()
  File "/Users/guichaoran/Downloads/Code/VideoLingo/st.py", line 114, in main
    text_processing_section()
  File "/Users/guichaoran/Downloads/Code/VideoLingo/st.py", line 30, in text_processing_section
    process_text()
  File "/Users/guichaoran/Downloads/Code/VideoLingo/st.py", line 53, in process_text
    step4_2_translate_all.translate_all()
  File "/Users/guichaoran/Downloads/Code/VideoLingo/core/step4_2_translate_all.py", line 82, in translate_all
    results.append(future.result())
  File "/opt/anaconda3/envs/videolingo/lib/python3.10/concurrent/futures/_base.py", line 438, in result
    return self.__get_result()
  File "/opt/anaconda3/envs/videolingo/lib/python3.10/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/opt/anaconda3/envs/videolingo/lib/python3.10/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/guichaoran/Downloads/Code/VideoLingo/core/step4_2_translate_all.py", line 48, in translate_chunk
    translation, english_result = translate_lines(chunk, previous_content_prompt, after_content_prompt, things_to_note_prompt, theme_prompt, i)
  File "/Users/guichaoran/Downloads/Code/VideoLingo/core/translate_once.py", line 63, in translate_lines
    express_result = retry_translation(prompt2, 'expressiveness')
  File "/Users/guichaoran/Downloads/Code/VideoLingo/core/translate_once.py", line 52, in retry_translation
    raise ValueError(f'[red]❌ {step_name.capitalize()} translation of block {index} failed after 3 retries. Please check your input text.[/red]')
ValueError: [red]❌ Expressiveness translation of block 82 failed after 3 retries. Please check your input text.[/red]
2024-10-21 23:53:27.042 Examining the path of torch.classes raised: Tried to instantiate class '__path__._path', but it does not exist! Ensure that it is registered via torch::class_

**Comment by Huanshere** [comment]
请问使用的什么 llm？

**Comment by tomridder** [comment]
3.5。准备再用4试试看

**Comment by Huanshere** [comment]
建议使用强的模型，小的模型容易不遵循格式报错

**Comment by tomridder** [comment]
[error.json](https://github.com/user-attachments/files/17487906/error.json)

用你的网站的sonnet 也是一样的报错
这个是日志附件

**Comment by Huanshere** [comment]
检查看看这里面写的 model 是什么😧

**Comment by Huanshere** [comment]
更新最新代码，新版不检查空行错误
