### ISSUE TITLE
LocalEntryNotFoundError: 

### ISSUE THREAD

**Issue by zlchs1312004** [Huanshere/VideoLingo#173]
处理字幕时出现以下报错, 搜遍了全网也没找到解决方案, 请作者指教

Traceback (most recent call last):
  File "F:\Programs\anaconda3\envs\videolingo\lib\site-packages\streamlit\runtime\scriptrunner\exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
  File "F:\Programs\anaconda3\envs\videolingo\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 590, in code_to_exec
    exec(code, module.__dict__)
  File "F:\AI\VideoLingo\VideoLingo\st.py", line 118, in <module>
    main()
  File "F:\AI\VideoLingo\VideoLingo\st.py", line 114, in main
    text_processing_section()
  File "F:\AI\VideoLingo\VideoLingo\st.py", line 30, in text_processing_section
    process_text()
  File "F:\AI\VideoLingo\VideoLingo\st.py", line 45, in process_text
    step2_whisper.transcribe()
  File "F:\AI\VideoLingo\VideoLingo\core\step2_whisper.py", line 23, in transcribe
    ts(video_file)
  File "F:\AI\VideoLingo\VideoLingo\core\all_whisper_methods\whisperX.py", line 134, in transcribe
    result = transcribe_audio(audio_file, start, end)
  File "F:\AI\VideoLingo\VideoLingo\core\all_whisper_methods\whisperX.py", line 56, in transcribe_audio
    model = whisperx.load_model(model_name, device, compute_type=compute_type, download_root=whisperx_model_dir)
  File "f:\ai\videolingo\videolingo\third_party\whisperx\whisperx\asr.py", line 288, in load_model
    model = model or WhisperModel(whisper_arch,
  File "F:\Programs\anaconda3\envs\videolingo\lib\site-packages\faster_whisper\transcribe.py", line 127, in __init__
    model_path = download_model(
  File "F:\Programs\anaconda3\envs\videolingo\lib\site-packages\faster_whisper\utils.py", line 119, in download_model
    return huggingface_hub.snapshot_download(repo_id, **kwargs)
  File "F:\Programs\anaconda3\envs\videolingo\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "F:\Programs\anaconda3\envs\videolingo\lib\site-packages\huggingface_hub\_snapshot_download.py", line 219, in snapshot_download
    raise LocalEntryNotFoundError(
huggingface_hub.errors.LocalEntryNotFoundError: Cannot find an appropriate cached snapshot folder for the specified revision on the local disk and outgoing traffic has been disabled. To enable repo look-ups and downloads online, pass 'local_files_only=False' as input.

![Untitled-2](https://github.com/user-attachments/assets/b78fbc66-e54b-4967-97a0-710e179a195d)

**Comment by Huanshere** [comment]
这是由于你的梯子无法连接 huggingface.co 导致的验证失败，请搜索如何让命令行能够访问外网，然后 ping 一下 hf 试试～
