### ISSUE TITLE
依旧报错 : ❎ API response error: Empty value for sub-key 'free' in item 6，用的是 claude-3.5

### ISSUE THREAD

**Issue by tomridder** [Huanshere/VideoLingo#178]
2024-10-23 23:04:17.736 Uncaught app exception
Traceback (most recent call last):
  File "/Users/guichaoran/Downloads/Code/VideoLingo/core/ask_gpt.py", line 82, in ask_gpt
    raise ValueError(f"❎ API response error: {valid_response['message']}")
ValueError: ❎ API response error: Empty value for sub-key 'free' in item 6

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/guichaoran/Downloads/Code/VideoLingo/core/ask_gpt.py", line 90, in ask_gpt
    raise Exception(f"JSON parsing still failed after {max_retries} attempts: {e}\n Please check your network connection or API key or `output/gpt_log/error.json` to debug.")
Exception: JSON parsing still failed after 3 attempts: ❎ API response error: Empty value for sub-key 'free' in item 6
 Please check your network connection or API key or `output/gpt_log/error.json` to debug.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/videolingo/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
  File "/opt/anaconda3/envs/videolingo/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 590, in code_to_exec
    exec(code, module.__dict__)
  File "/Users/guichaoran/Downloads/Code/VideoLingo/st.py", line 118, in <module>
    main()
  File "/Users/guichaoran/Downloads/Code/VideoLingo/st.py", line 114, in main
    text_processing_section()
  File "/Users/guichaoran/Downloads/Code/VideoLingo/st.py", line 30, in text_processing_section
    process_text()
  File "/Users/guichaoran/Downloads/Code/VideoLingo/st.py", line 53, in process_text
    step4_2_translate_all.translate_all()
  File "/Users/guichaoran/Downloads/Code/VideoLingo/core/step4_2_translate_all.py", line 82, in translate_all
    results.append(future.result())
  File "/opt/anaconda3/envs/videolingo/lib/python3.10/concurrent/futures/_base.py", line 438, in result
    return self.__get_result()
  File "/opt/anaconda3/envs/videolingo/lib/python3.10/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/opt/anaconda3/envs/videolingo/lib/python3.10/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/guichaoran/Downloads/Code/VideoLingo/core/step4_2_translate_all.py", line 48, in translate_chunk
    translation, english_result = translate_lines(chunk, previous_content_prompt, after_content_prompt, things_to_note_prompt, theme_prompt, i)
  File "/Users/guichaoran/Downloads/Code/VideoLingo/core/translate_once.py", line 63, in translate_lines
    express_result = retry_translation(prompt2, 'expressiveness')
  File "/Users/guichaoran/Downloads/Code/VideoLingo/core/translate_once.py", line 47, in retry_translation
    result = ask_gpt(prompt, response_json=True, valid_def=valid_express, log_title=f'translate_{step_name}')
  File "/Users/guichaoran/Downloads/Code/VideoLingo/core/ask_gpt.py", line 103, in ask_gpt
    raise Exception(f"Still failed after {max_retries} attempts: {e}")
Exception: Still failed after 3 attempts: JSON parsing still failed after 3 attempts: ❎ API response error: Empty value for sub-key 'free' in item 6
 Please check your network connection or API key or `output/gpt_log/error.json` to debug.

[error.json](https://github.com/user-attachments/files/17494234/error.json)

**Comment by tomridder** [comment]
点击重试了以后 规避了～

**Comment by tomridder** [comment]
点击重试了以后 规避了～
