### ISSUE TITLE
翻译超长视频时出现Expressiveness translation of block 9 failed after 3 retries. Please check your input text.

### ISSUE THREAD

**Issue by ysxk** [Huanshere/VideoLingo#181]
原视频：https://www.youtube.com/watch?v=Sc48ToLIQAY
我用的视频不是解析的，是我自己已经下载到本地的视频
处理字幕时出现报错
环境：使用python3.10.11创建的venv虚拟环境
显卡：2060s，8g显存，cpu：12490f，32g内存
windows 10 
cuda11.8和12.6都安装了
cudnn也安装了，测试翻译短时间的视频没有出问题
我尝试了几次，都是在翻译到这个固定的位置时报错
具体报错时长见文末附图
详细报错：
│ -------------------------------------------------- │
│ Origin:  Congratulations, class of 2024.           │
│ Direct:  祝贺2024届毕业生。                        │
│ Free:    恭喜2024届毕业生！                        │
│ -------------------------------------------------- │
│ Origin:  Go get them.                              │
│ Direct:  加油！                                    │
│ Free:    加油！                                    │
╰────────────────────────────────────────────────────╯
2024-10-24 17:50:13.540 Uncaught app exception
Traceback (most recent call last):
  File "F:\videolingo\VideoLingo\venv\lib\site-packages\streamlit\runtime\scriptrunner\exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
  File "F:\videolingo\VideoLingo\venv\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 590, in code_to_exec
    exec(code, module.__dict__)
  File "F:\videolingo\VideoLingo\st.py", line 118, in <module>
    main()
  File "F:\videolingo\VideoLingo\st.py", line 114, in main
    text_processing_section()
  File "F:\videolingo\VideoLingo\st.py", line 30, in text_processing_section
    process_text()
  File "F:\videolingo\VideoLingo\st.py", line 53, in process_text
    step4_2_translate_all.translate_all()
  File "F:\videolingo\VideoLingo\core\step4_2_translate_all.py", line 82, in translate_all
    results.append(future.result())
  File "F:\videolingo\VideoLingo\runtime\lib\concurrent\futures\_base.py", line 451, in result
    return self.__get_result()
  File "F:\videolingo\VideoLingo\runtime\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "F:\videolingo\VideoLingo\runtime\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "F:\videolingo\VideoLingo\core\step4_2_translate_all.py", line 48, in translate_chunk
    translation, english_result = translate_lines(chunk, previous_content_prompt, after_content_prompt, things_to_note_prompt, theme_prompt, i)
  File "F:\videolingo\VideoLingo\core\translate_once.py", line 63, in translate_lines
    express_result = retry_translation(prompt2, 'expressiveness')
  File "F:\videolingo\VideoLingo\core\translate_once.py", line 52, in retry_translation
    raise ValueError(f'[red]❌ {step_name.capitalize()} translation of block {index} failed after 3 retries. Please check your input text.[/red]')
ValueError: [red]❌ Expressiveness translation of block 9 failed after 3 retries. Please check your input text.[/red]

![image](https://github.com/user-attachments/assets/11a0b0f7-079c-445f-a104-f12cc726593a)

**Comment by ysxk** [comment]
> 检查 output/gpt_log/error.json 看看是什么原因导致的错误。可能【空响应，拒绝翻译，格式错误】，另外 使用的是什么llm呢？

使用的api是https://github.com/chatanywhere/GPT_API_free的公益api
模型选择的是gpt3.5-turbo
具体报错原因已经找到，应该是api的免费额度用完了，我今天再次复现发现没有该报错了
