### ISSUE TITLE
建议增加报错块手动处理功能

### ISSUE THREAD

**Issue by lonrencn** [Huanshere/VideoLingo#192]
Traceback (most recent call last):
  File "/home/lonren/disk1t/miniconda3/envs/videolingo/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
  File "/home/lonren/disk1t/miniconda3/envs/videolingo/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 590, in code_to_exec
    exec(code, module.__dict__)
  File "/mnt/disk2t/videolingo-project/VideoLingo/st.py", line 118, in <module>
    main()
  File "/mnt/disk2t/videolingo-project/VideoLingo/st.py", line 114, in main
    text_processing_section()
  File "/mnt/disk2t/videolingo-project/VideoLingo/st.py", line 30, in text_processing_section
    process_text()
  File "/mnt/disk2t/videolingo-project/VideoLingo/st.py", line 53, in process_text
    step4_2_translate_all.translate_all()
  File "/mnt/disk2t/videolingo-project/VideoLingo/core/step4_2_translate_all.py", line 82, in translate_all
    results.append(future.result())
  File "/home/lonren/disk1t/miniconda3/envs/videolingo/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/home/lonren/disk1t/miniconda3/envs/videolingo/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/home/lonren/disk1t/miniconda3/envs/videolingo/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/mnt/disk2t/videolingo-project/VideoLingo/core/step4_2_translate_all.py", line 48, in translate_chunk
    translation, english_result = translate_lines(chunk, previous_content_prompt, after_content_prompt, things_to_note_prompt, theme_prompt, i)
  File "/mnt/disk2t/videolingo-project/VideoLingo/core/translate_once.py", line 63, in translate_lines
    express_result = retry_translation(prompt2, 'expressiveness')
  File "/mnt/disk2t/videolingo-project/VideoLingo/core/translate_once.py", line 52, in retry_translation
    raise ValueError(f'[red]❌ {step_name.capitalize()} translation of block {index} failed after 3 retries. Please check your input text.[/red]')
ValueError: [red]❌ Expressiveness translation of block 17 failed after 3 retries. Please check your input text.[/red]

建议代码能定位到   block 17   的位置，可以手动处理一下，或者第三次失败填充个标识符什么的，让转录视频前，让用户自己手动处理。

**Comment by Huanshere** [comment]
嗯最近在忙着开发SaaS版本，开源版本有许多不稳定的地方，请问是否使用的claude3.5?

**Comment by lonrencn** [comment]
> 嗯最近在忙着开发SaaS版本，开源版本有许多不稳定的地方，请问是否使用的claude3.5?

不是，本地大模型

**Comment by Huanshere** [comment]
具体为什么小模型会报错在文档中有说明，这类报错问题本项目暂不考虑修复
