### ISSUE TITLE
启动streamlt后，一直出现下面错误，该怎么搞？

### ISSUE THREAD

**Issue by wsz168** [Huanshere/VideoLingo#21]
2024-08-27 17:12:41.052 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\alisu\AppData\Local\Programs\Python\Python311\Lib\site-packages\streamlit\runtime\scriptrunner\exec_code.py", line 85, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "C:\Users\alisu\AppData\Local\Programs\Python\Python311\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 576, in code_to_exec
    exec(code, module.__dict__)
  File "D:\Test\VideoLingo\st.py", line 5, in <module>
    from core import step1_ytdlp, step2_whisper_stamped, step3_1_spacy_split, step3_2_splitbymeaning
  File "D:\Test\VideoLingo\core\step3_2_splitbymeaning.py", line 58
    print(f"📚 Split Sentence: {best_split.replace(r'\n', ' [br] ')}")
                                                                    ^
SyntaxError: f-string expression part cannot include a backslash

**Comment by Huanshere** [comment]
这是因为 python 版本不是 3.12 有点格式问题，可以吧对应文件的 print 删掉，或者换 3.12 环境
