### ISSUE TITLE
whisper报sha 256 错误 但是我校验过是没问题的 RuntimeError: Model has been downloaded but the SHA256 checksum does not not match. Please retry loading the model.

### ISSUE THREAD

**Issue by ysxk** [Huanshere/VideoLingo#221]
环境：
系统：win11
python 3.10.0
显卡 3060 
cuda118和cuda126还有cudnn9.3都安装了，环境变量也加了
whisper 模型，不管是自己手动下载，还是从我别的能正常使用videolingo的电脑传过来的模型，各种方法都测试了
也手动校验过sha256，sha256是能对的上的，但是就是会提示这个报错
实测不管什么模型都会提示这个错误
完整报错：

WhisperX processing error: Model has been downloaded but the SHA256 checksum does not not match. Please retry loading
the model.
2024-10-30 16:07:04.175 Uncaught app exception
Traceback (most recent call last):
  File "E:\anaconda3\envs\videolingo\lib\site-packages\streamlit\runtime\scriptrunner\exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
  File "E:\anaconda3\envs\videolingo\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 590, in code_to_exec
    exec(code, module.__dict__)
  File "E:\VideoLingo\VideoLingo\st.py", line 117, in <module>
    main()
  File "E:\VideoLingo\VideoLingo\st.py", line 113, in main
    text_processing_section()
  File "E:\VideoLingo\VideoLingo\st.py", line 30, in text_processing_section
    process_text()
  File "E:\VideoLingo\VideoLingo\st.py", line 45, in process_text
    step2_whisper.transcribe()
  File "E:\VideoLingo\VideoLingo\core\step2_whisper.py", line 13, in transcribe
    ts(video_file)
  File "E:\VideoLingo\VideoLingo\core\all_whisper_methods\whisperX.py", line 142, in transcribe
    result = transcribe_audio(audio_file, start, end)
  File "E:\VideoLingo\VideoLingo\core\all_whisper_methods\whisperX.py", line 59, in transcribe_audio
    model = whisperx.load_model(model_name, device, compute_type=compute_type, language=whisper_language, vad_options=vad_options, asr_options=asr_options, download_root=MODEL_DIR)
  File "e:\videolingo\videolingo\third_party\whisperx\whisperx\asr.py", line 347, in load_model
    vad_model = load_vad_model(torch.device(device), use_auth_token=None, **default_vad_options)
  File "e:\videolingo\videolingo\third_party\whisperx\whisperx\vad.py", line 47, in load_vad_model
    raise RuntimeError(
RuntimeError: Model has been downloaded but the SHA256 checksum does not not match. Please retry loading the model.

**Comment by ysxk** [comment]
目前已解决
方案：

1：修改whisperx下的asr.py（是pip安装的whisper，不是video目录下的whisperx，具体路径跟自己环境有关）
在322行之后加上
        "max_new_tokens": None,
        "clip_timestamps": None,
        "hallucination_silence_threshold": None,
这三个参数:
2：~/.cache/torch/下的whisperx-vad-segmentation.bin

**Comment by Huanshere** [comment]
建议使用 VideoLingo v1.7 新版，可以选择手动下载模型放在 model cache ，这样可以跳过哈希验证
