### ISSUE TITLE
接口超过重试次数上限时报错

### ISSUE THREAD

**Issue by DeepFal** [Huanshere/VideoLingo#239]
当接口请求超过默认次数3次时，会直接抛错程序停止运行
希望能够给用户检查网络的机会，在超过自动重试次数时打断等待用户输入或等待回调，检查完成后用户进行手动重试，来实现保留翻译进度的目的，节省token消耗和时间
```
INFO:openai._base_client:Retrying request to /chat/completions in 0.982517 seconds
2024-11-07 21:35:35.905 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\deepf\anaconda3\envs\videolingo\lib\site-packages\httpx\_transports\default.py", line 72, in map_httpcore_exceptions
    yield
  File "C:\Users\deepf\anaconda3\envs\videolingo\lib\site-packages\httpx\_transports\default.py", line 236, in handle_request
    resp = self._pool.handle_request(req)
  File "C:\Users\deepf\anaconda3\envs\videolingo\lib\site-packages\httpcore\_sync\connection_pool.py", line 216, in handle_request
    raise exc from None
  File "C:\Users\deepf\anaconda3\envs\videolingo\lib\site-packages\httpcore\_sync\connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
  File "C:\Users\deepf\anaconda3\envs\videolingo\lib\site-packages\httpcore\_sync\http_proxy.py", line 289, in handle_request
    connect_response = self._connection.handle_request(
  File "C:\Users\deepf\anaconda3\envs\videolingo\lib\site-packages\httpcore\_sync\connection.py", line 99, in handle_request
    raise exc
  File "C:\Users\deepf\anaconda3\envs\videolingo\lib\site-packages\httpcore\_sync\connection.py", line 76, in handle_request
    stream = self._connect(request)
  File "C:\Users\deepf\anaconda3\envs\videolingo\lib\site-packages\httpcore\_sync\connection.py", line 154, in _connect
    stream = stream.start_tls(**kwargs)
  File "C:\Users\deepf\anaconda3\envs\videolingo\lib\site-packages\httpcore\_backends\sync.py", line 152, in start_tls
    with map_exceptions(exc_map):
  File "C:\Users\deepf\anaconda3\envs\videolingo\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\deepf\anaconda3\envs\videolingo\lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: EOF occurred in violation of protocol (_ssl.c:997)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\deepf\anaconda3\envs\videolingo\lib\site-packages\openai\_base_client.py", line 981, in _request
    response = self._client.send(
  File "C:\Users\deepf\anaconda3\envs\videolingo\lib\site-packages\httpx\_client.py", line 926, in send
    response = self._send_handling_auth(
  File "C:\Users\deepf\anaconda3\envs\videolingo\lib\site-packages\httpx\_client.py", line 954, in _send_handling_auth
    response = self._send_handling_redirects(
  File "C:\Users\deepf\anaconda3\envs\videolingo\lib\site-packages\httpx\_client.py", line 991, in _send_handling_redirects
    response = self._send_single_request(request)
  File "C:\Users\deepf\anaconda3\envs\videolingo\lib\site-packages\httpx\_client.py", line 1027, in _send_single_request
    response = transport.handle_request(request)
  File "C:\Users\deepf\anaconda3\envs\videolingo\lib\site-packages\httpx\_transports\default.py", line 235, in handle_request
    with map_httpcore_exceptions():
  File "C:\Users\deepf\anaconda3\envs\videolingo\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\deepf\anaconda3\envs\videolingo\lib\site-packages\httpx\_transports\default.py", line 89, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: EOF occurred in violation of protocol (_ssl.c:997)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\deepf\Desktop\VideoLingo\VideoLingo\core\ask_gpt.py", line 66, in ask_gpt
    response = client.chat.completions.create(
  File "C:\Users\deepf\anaconda3\envs\videolingo\lib\site-packages\openai\_utils\_utils.py", line 274, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\deepf\anaconda3\envs\videolingo\lib\site-packages\openai\resources\chat\completions.py", line 704, in create
    return self._post(
  File "C:\Users\deepf\anaconda3\envs\videolingo\lib\site-packages\openai\_base_client.py", line 1268, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "C:\Users\deepf\anaconda3\envs\videolingo\lib\site-packages\openai\_base_client.py", line 945, in request
    return self._request(
  File "C:\Users\deepf\anaconda3\envs\videolingo\lib\site-packages\openai\_base_client.py", line 1005, in _request
    return self._retry_request(
  File "C:\Users\deepf\anaconda3\envs\videolingo\lib\site-packages\openai\_base_client.py", line 1083, in _retry_request
    return self._request(
  File "C:\Users\deepf\anaconda3\envs\videolingo\lib\site-packages\openai\_base_client.py", line 1005, in _request
    return self._retry_request(
  File "C:\Users\deepf\anaconda3\envs\videolingo\lib\site-packages\openai\_base_client.py", line 1083, in _retry_request
    return self._request(
  File "C:\Users\deepf\anaconda3\envs\videolingo\lib\site-packages\openai\_base_client.py", line 1015, in _request
    raise APIConnectionError(request=request) from err
openai.APIConnectionError: Connection error.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\deepf\anaconda3\envs\videolingo\lib\site-packages\streamlit\runtime\scriptrunner\exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
  File "C:\Users\deepf\anaconda3\envs\videolingo\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 590, in code_to_exec
    exec(code, module.__dict__)
  File "C:\Users\deepf\Desktop\VideoLingo\VideoLingo\st.py", line 117, in <module>
    main()
  File "C:\Users\deepf\Desktop\VideoLingo\VideoLingo\st.py", line 113, in main
    text_processing_section()
  File "C:\Users\deepf\Desktop\VideoLingo\VideoLingo\st.py", line 30, in text_processing_section
    process_text()
  File "C:\Users\deepf\Desktop\VideoLingo\VideoLingo\st.py", line 48, in process_text
    step3_2_splitbymeaning.split_sentences_by_meaning()
  File "C:\Users\deepf\Desktop\VideoLingo\VideoLingo\core\step3_2_splitbymeaning.py", line 118, in split_sentences_by_meaning
    sentences = parallel_split_sentences(sentences, max_length=load_key("max_split_length"), max_workers=load_key("max_workers"), nlp=nlp, retry_attempt=retry_attempt)
  File "C:\Users\deepf\Desktop\VideoLingo\VideoLingo\core\step3_2_splitbymeaning.py", line 100, in parallel_split_sentences
    split_result = future.result()
  File "C:\Users\deepf\anaconda3\envs\videolingo\lib\concurrent\futures\_base.py", line 445, in result
    return self.__get_result()
  File "C:\Users\deepf\anaconda3\envs\videolingo\lib\concurrent\futures\_base.py", line 390, in __get_result
    raise self._exception
  File "C:\Users\deepf\anaconda3\envs\videolingo\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\deepf\Desktop\VideoLingo\VideoLingo\core\step3_2_splitbymeaning.py", line 59, in split_sentence
    response_data = ask_gpt(split_prompt + ' ' * retry_attempt, response_json=True, valid_def=valid_split, log_title='sentence_splitbymeaning')
  File "C:\Users\deepf\Desktop\VideoLingo\VideoLingo\core\ask_gpt.py", line 103, in ask_gpt
    raise Exception(f"Still failed after {max_retries} attempts: {e}")
Exception: Still failed after 3 attempts: Connection error.
```

**Comment by DeepFal** [comment]
> 当接口请求超过默认次数3次时，会直接抛错程序停止运行 希望能够给用户 检查网络 或 等待请求接口过于频繁的冷却时间 的机会，在超过自动重试次数时打断等待用户输入或等待回调，检查完成后用户进行手动重试，来实现保留翻译进度的目的，节省token消耗和时间
> 
> ```
> INFO:openai._base_client:Retrying request to /chat/completions in 0.982517 seconds
> 2024-11-07 21:35:35.905 Uncaught app exception
> Traceback (most recent call last):
>   File "C:\Users\deepf\anaconda3\envs\videolingo\lib\site-packages\httpx\_transports\default.py", line 72, in map_httpcore_exceptions
>     yield
>   File "C:\Users\deepf\anaconda3\envs\videolingo\lib\site-packages\httpx\_transports\default.py", line 236, in handle_request
>     resp = self._pool.handle_request(req)
>   File "C:\Users\deepf\anaconda3\envs\videolingo\lib\site-packages\httpcore\_sync\connection_pool.py", line 216, in handle_request
>     raise exc from None
>   File "C:\Users\deepf\anaconda3\envs\videolingo\lib\site-packages\httpcore\_sync\connection_pool.py", line 196, in handle_request
>     response = connection.handle_request(
>   File "C:\Users\deepf\anaconda3\envs\videolingo\lib\site-packages\httpcore\_sync\http_proxy.py", line 289, in handle_request
>     connect_response = self._connection.handle_request(
>   File "C:\Users\deepf\anaconda3\envs\videolingo\lib\site-packages\httpcore\_sync\connection.py", line 99, in handle_request
>     raise exc
>   File "C:\Users\deepf\anaconda3\envs\videolingo\lib\site-packages\httpcore\_sync\connection.py", line 76, in handle_request
>     stream = self._connect(request)
>   File "C:\Users\deepf\anaconda3\envs\videolingo\lib\site-packages\httpcore\_sync\connection.py", line 154, in _connect
>     stream = stream.start_tls(**kwargs)
>   File "C:\Users\deepf\anaconda3\envs\videolingo\lib\site-packages\httpcore\_backends\sync.py", line 152, in start_tls
>     with map_exceptions(exc_map):
>   File "C:\Users\deepf\anaconda3\envs\videolingo\lib\contextlib.py", line 153, in __exit__
>     self.gen.throw(typ, value, traceback)
>   File "C:\Users\deepf\anaconda3\envs\videolingo\lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
>     raise to_exc(exc) from exc
> httpcore.ConnectError: EOF occurred in violation of protocol (_ssl.c:997)
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "C:\Users\deepf\anaconda3\envs\videolingo\lib\site-packages\openai\_base_client.py", line 981, in _request
>     response = self._client.send(
>   File "C:\Users\deepf\anaconda3\envs\videolingo\lib\site-packages\httpx\_client.py", line 926, in send
>     response = self._send_handling_auth(
>   File "C:\Users\deepf\anaconda3\envs\videolingo\lib\site-packages\httpx\_client.py", line 954, in _send_handling_auth
>     response = self._send_handling_redirects(
>   File "C:\Users\deepf\anaconda3\envs\videolingo\lib\site-packages\httpx\_client.py", line 991, in _send_handling_redirects
>     response = self._send_single_request(request)
>   File "C:\Users\deepf\anaconda3\envs\videolingo\lib\site-packages\httpx\_client.py", line 1027, in _send_single_request
>     response = transport.handle_request(request)
>   File "C:\Users\deepf\anaconda3\envs\videolingo\lib\site-packages\httpx\_transports\default.py", line 235, in handle_request
>     with map_httpcore_exceptions():
>   File "C:\Users\deepf\anaconda3\envs\videolingo\lib\contextlib.py", line 153, in __exit__
>     self.gen.throw(typ, value, traceback)
>   File "C:\Users\deepf\anaconda3\envs\videolingo\lib\site-packages\httpx\_transports\default.py", line 89, in map_httpcore_exceptions
>     raise mapped_exc(message) from exc
> httpx.ConnectError: EOF occurred in violation of protocol (_ssl.c:997)
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "C:\Users\deepf\Desktop\VideoLingo\VideoLingo\core\ask_gpt.py", line 66, in ask_gpt
>     response = client.chat.completions.create(
>   File "C:\Users\deepf\anaconda3\envs\videolingo\lib\site-packages\openai\_utils\_utils.py", line 274, in wrapper
>     return func(*args, **kwargs)
>   File "C:\Users\deepf\anaconda3\envs\videolingo\lib\site-packages\openai\resources\chat\completions.py", line 704, in create
>     return self._post(
>   File "C:\Users\deepf\anaconda3\envs\videolingo\lib\site-packages\openai\_base_client.py", line 1268, in post
>     return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
>   File "C:\Users\deepf\anaconda3\envs\videolingo\lib\site-packages\openai\_base_client.py", line 945, in request
>     return self._request(
>   File "C:\Users\deepf\anaconda3\envs\videolingo\lib\site-packages\openai\_base_client.py", line 1005, in _request
>     return self._retry_request(
>   File "C:\Users\deepf\anaconda3\envs\videolingo\lib\site-packages\openai\_base_client.py", line 1083, in _retry_request
>     return self._request(
>   File "C:\Users\deepf\anaconda3\envs\videolingo\lib\site-packages\openai\_base_client.py", line 1005, in _request
>     return self._retry_request(
>   File "C:\Users\deepf\anaconda3\envs\videolingo\lib\site-packages\openai\_base_client.py", line 1083, in _retry_request
>     return self._request(
>   File "C:\Users\deepf\anaconda3\envs\videolingo\lib\site-packages\openai\_base_client.py", line 1015, in _request
>     raise APIConnectionError(request=request) from err
> openai.APIConnectionError: Connection error.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\deepf\anaconda3\envs\videolingo\lib\site-packages\streamlit\runtime\scriptrunner\exec_code.py", line 88, in exec_func_with_error_handling
>     result = func()
>   File "C:\Users\deepf\anaconda3\envs\videolingo\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 590, in code_to_exec
>     exec(code, module.__dict__)
>   File "C:\Users\deepf\Desktop\VideoLingo\VideoLingo\st.py", line 117, in <module>
>     main()
>   File "C:\Users\deepf\Desktop\VideoLingo\VideoLingo\st.py", line 113, in main
>     text_processing_section()
>   File "C:\Users\deepf\Desktop\VideoLingo\VideoLingo\st.py", line 30, in text_processing_section
>     process_text()
>   File "C:\Users\deepf\Desktop\VideoLingo\VideoLingo\st.py", line 48, in process_text
>     step3_2_splitbymeaning.split_sentences_by_meaning()
>   File "C:\Users\deepf\Desktop\VideoLingo\VideoLingo\core\step3_2_splitbymeaning.py", line 118, in split_sentences_by_meaning
>     sentences = parallel_split_sentences(sentences, max_length=load_key("max_split_length"), max_workers=load_key("max_workers"), nlp=nlp, retry_attempt=retry_attempt)
>   File "C:\Users\deepf\Desktop\VideoLingo\VideoLingo\core\step3_2_splitbymeaning.py", line 100, in parallel_split_sentences
>     split_result = future.result()
>   File "C:\Users\deepf\anaconda3\envs\videolingo\lib\concurrent\futures\_base.py", line 445, in result
>     return self.__get_result()
>   File "C:\Users\deepf\anaconda3\envs\videolingo\lib\concurrent\futures\_base.py", line 390, in __get_result
>     raise self._exception
>   File "C:\Users\deepf\anaconda3\envs\videolingo\lib\concurrent\futures\thread.py", line 52, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "C:\Users\deepf\Desktop\VideoLingo\VideoLingo\core\step3_2_splitbymeaning.py", line 59, in split_sentence
>     response_data = ask_gpt(split_prompt + ' ' * retry_attempt, response_json=True, valid_def=valid_split, log_title='sentence_splitbymeaning')
>   File "C:\Users\deepf\Desktop\VideoLingo\VideoLingo\core\ask_gpt.py", line 103, in ask_gpt
>     raise Exception(f"Still failed after {max_retries} attempts: {e}")
> Exception: Still failed after 3 attempts: Connection error.
> ```

**Comment by Huanshere** [comment]
gpt log 会被保存，重新执行不会重复访问已经访问过的

**Comment by DeepFal** [comment]
> gpt log 会被保存，重新执行不会重复访问已经访问过的

没问题，接口突然失效了，测试接口报的错，不是翻译流程
