### ISSUE TITLE
完成Translating chunks后报错，多次重试依然报错

### ISSUE THREAD

**Issue by Github37525** [Huanshere/VideoLingo#241]
2024-11-08 10:59:31.609 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\jackyqin\anaconda3\envs\videolingo\lib\site-packages\streamlit\runtime\scriptrunner\exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
  File "C:\Users\jackyqin\anaconda3\envs\videolingo\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 590, in code_to_exec
    exec(code, module.__dict__)
  File "C:\Users\jackyqin\Desktop\VideoLingo\st.py", line 117, in <module>
    main()
  File "C:\Users\jackyqin\Desktop\VideoLingo\st.py", line 113, in main
    text_processing_section()
  File "C:\Users\jackyqin\Desktop\VideoLingo\st.py", line 30, in text_processing_section
    process_text()
  File "C:\Users\jackyqin\Desktop\VideoLingo\st.py", line 53, in process_text
    step4_2_translate_all.translate_all()
  File "C:\Users\jackyqin\Desktop\VideoLingo\core\step4_2_translate_all.py", line 82, in translate_all
    results.append(future.result())
  File "C:\Users\jackyqin\anaconda3\envs\videolingo\lib\concurrent\futures\_base.py", line 438, in result
    return self.__get_result()
  File "C:\Users\jackyqin\anaconda3\envs\videolingo\lib\concurrent\futures\_base.py", line 390, in __get_result
    raise self._exception
  File "C:\Users\jackyqin\anaconda3\envs\videolingo\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\jackyqin\Desktop\VideoLingo\core\step4_2_translate_all.py", line 48, in translate_chunk
    translation, english_result = translate_lines(chunk, previous_content_prompt, after_content_prompt, things_to_note_prompt, theme_prompt, i)
  File "C:\Users\jackyqin\Desktop\VideoLingo\core\translate_once.py", line 54, in translate_lines
    express_result = retry_translation(prompt2, 'expressiveness')
  File "C:\Users\jackyqin\Desktop\VideoLingo\core\translate_once.py", line 43, in retry_translation
    raise ValueError(f'[red]❌ {step_name.capitalize()} translation of block {index} failed after 3 retries. Please check your input text.[/red]')
ValueError: [red]❌ Expressiveness translation of block 9 failed after 3 retries. Please check your input text.[/red]

**Comment by Huanshere** [comment]
可能是网络原因也可能是拒绝翻译，可以检查 error.json看看具体错误

**Comment by misslxs** [comment]
> 可能是网络原因也可能是拒绝翻译，可以检查 error.json看看具体错误


请问 error.json 中报错大多数是以下内容，应该如何处理呢

"message": "Missing required sub-key(s) in item 5: free"
 "message": "json_repair parsing failed."

**Comment by gaspire** [comment]
我使用 ollama 的 Qwen2.5 72B，也同样报错："message": "json_repair parsing failed."

**Comment by Huanshere** [comment]
ollama 本地运行大模型很容易出现长文本不稳定或者提前截断等问题，例如你可以试试丢入一个长文本让它用 json 格式生成总结。因此我更建议调用稳定 api，例如硅基流动的。
