### ISSUE TITLE
运行报错No module named 'julius'

### ISSUE THREAD

**Issue by Brzjomo** [Huanshere/VideoLingo#245]
python版本3.10.0，安装也正确的，运行就报错。有人知道怎么解决吗？
```
(videolingo) E:\VideoLingo\VideoLingo>python st.py
Traceback (most recent call last):
  File "E:\VideoLingo\VideoLingo\st.py", line 3, in <module>
    from st_components.imports_and_utils import *
  File "E:\VideoLingo\VideoLingo\st_components\imports_and_utils.py", line 3, in <module>
    from core import step2_whisper, step1_ytdlp, step3_1_spacy_split, step3_2_splitbymeaning, step9_extract_refer_audio
  File "E:\VideoLingo\VideoLingo\core\step9_extract_refer_audio.py", line 10, in <module>
    from core.all_whisper_methods.whisperXapi import AUDIO_DIR, VOCAL_AUDIO_FILE
  File "E:\VideoLingo\VideoLingo\core\all_whisper_methods\whisperXapi.py", line 8, in <module>
    from core.all_whisper_methods.demucs_vl import demucs_main
  File "E:\VideoLingo\VideoLingo\core\all_whisper_methods\demucs_vl.py", line 5, in <module>
    from demucs.pretrained import get_model
  File "C:\Users\Admin\anaconda3\envs\videolingo\lib\site-packages\demucs\pretrained.py", line 15, in <module>
    from .hdemucs import HDemucs
  File "C:\Users\Admin\anaconda3\envs\videolingo\lib\site-packages\demucs\hdemucs.py", line 18, in <module>
    from .demucs import DConv, rescale_module
  File "C:\Users\Admin\anaconda3\envs\videolingo\lib\site-packages\demucs\demucs.py", line 10, in <module>
    import julius
ModuleNotFoundError: No module named 'julius'

(videolingo) E:\VideoLingo\VideoLingo>pip show julius
Name: julius
Version: 0.2.7
Summary: Nice DSP sweets: resampling, FFT Convolutions. All with PyTorch, differentiable and with CUDA support.
Home-page: https://github.com/adefossez/julius
Author: Alexandre Défossez
Author-email: alexandre.defossez@gmail.com
License: MIT License
Location: c:\users\Admin\anaconda3\envs\videolingo\lib\site-packages
Requires: torch
Required-by: demucs, torch-audiomentations

(videolingo) E:\VideoLingo\VideoLingo>
```

**Comment by Huanshere** [comment]
是否尝试过 `pip install julius` 进行修复? 没有遇到过这个问题

**Comment by Brzjomo** [comment]
试过了几次了，卸了再装也这样。还试过1.7.0的版本，都这样。后来不用Anaconda，设置默认环境python版本为3.10.0后直接装，就没报错。
还有pytorch版本用项目默认的2.0.0就只能用CPU运算，换成2.1.2就没问题了。
