### ISSUE TITLE
拉取最新git后安装出错

### ISSUE THREAD

**Issue by assassinliujie** [Huanshere/VideoLingo#269]
强制使用远程仓库覆盖本地，重新安装后仍旧这样
Traceback (most recent call last):
  File "/root/anaconda3/envs/videoaaa/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
  File "/root/anaconda3/envs/videoaaa/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 590, in code_to_exec
    exec(code, module.__dict__)
  File "/root/VideoLingo/st.py", line 3, in <module>
    from st_components.imports_and_utils import *
  File "/root/VideoLingo/st_components/imports_and_utils.py", line 3, in <module>
    from core import (
  File "/root/VideoLingo/core/step4_2_translate_all.py", line 8, in <module>
    from core.step8_1_gen_audio_task import check_len_then_trim
  File "/root/VideoLingo/core/step8_1_gen_audio_task.py", line 12, in <module>
    from core.all_tts_functions.estimate_duration import init_estimator, estimate_duration
  File "/root/VideoLingo/core/all_tts_functions/estimate_duration.py", line 3, in <module>
    from g2p_en import G2p
  File "/root/anaconda3/envs/videoaaa/lib/python3.10/site-packages/g2p_en/__init__.py", line 1, in <module>
    from .g2p import G2p
  File "/root/anaconda3/envs/videoaaa/lib/python3.10/site-packages/g2p_en/g2p.py", line 22, in <module>
    nltk.data.find('taggers/averaged_perceptron_tagger.zip')
  File "/root/anaconda3/envs/videoaaa/lib/python3.10/site-packages/nltk/data.py", line 538, in find
    return ZipFilePathPointer(p, zipentry)
  File "/root/anaconda3/envs/videoaaa/lib/python3.10/site-packages/nltk/data.py", line 391, in __init__
    zipfile = OpenOnDemandZipFile(os.path.abspath(zipfile))
  File "/root/anaconda3/envs/videoaaa/lib/python3.10/site-packages/nltk/data.py", line 1020, in __init__
    zipfile.ZipFile.__init__(self, filename)
  File "/root/anaconda3/envs/videoaaa/lib/python3.10/zipfile.py", line 1272, in __init__
    self._RealGetContents()
  File "/root/anaconda3/envs/videoaaa/lib/python3.10/zipfile.py", line 1339, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
^C  Stopping...

**Comment by assassinliujie** [comment]
一开始还不是这个问题，只是单纯的一直在网页加载页面，反复重启几次后就开始报错这个，重新下了这个zip文件之后又回到了一直在加载的状态，控制台也没有任何报错

**Comment by assassinliujie** [comment]
系统是ubuntu20.04

**Comment by assassinliujie** [comment]
现在尝试回退到之前版本也会这样卡住在加载界面不动
![图片](https://github.com/user-attachments/assets/3e62cefc-de03-4668-979d-18ad826fa72b)

**Comment by assassinliujie** [comment]
解决了，可能是因为网络问题，[nltk_data] Downloading package cmudict to /root/nltk_data...
[nltk_data]   Unzipping corpora/cmudict.zip.等了好久才在控制台出现提示，大概在十五分钟左右，之后就正常工作了。这是这个版本的新增内容吗，为什么会重新安装呢

**Comment by Huanshere** [comment]
是的， v2.0 引入了三个新的库，是为了后续更好的对齐配音加入的，通过拆解读音来预测文本的语速。 v1.8 的逻辑是按照长度，v2.0 是按照拼音或者音节
