### ISSUE TITLE
找不到 GPT-SoVITS-v2 目录或配置文件路径

### ISSUE THREAD

**Issue by qunyinghuicui-copy** [Huanshere/VideoLingo#279]
Attempt 1 failed, retrying...
TTS request failed, status code: 404
TTS request failed, switching back to mode 2 and retrying
TTS request failed, status code: 404
❌ Error: Failed to get audio duration: list index out of range
Attempt 2 failed, retrying...
TTS request failed, status code: 404
TTS request failed, switching back to mode 2 and retrying
TTS request failed, status code: 404
❌ Error: Failed to get audio duration: list index out of range
❌ Error in warmup: Failed to generate audio after 3 attempts: Generated audio duration is 0
🔄 Generating TTS audio... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% -:--:--
2024-11-22 21:48:59.690 Uncaught app exception
Traceback (most recent call last):
  File "D:\dub\VideoLingo\core\all_tts_functions\tts_main.py", line 52, in tts_main
    raise Exception("Generated audio duration is 0")
Exception: Generated audio duration is 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda\envs\videolingo\lib\site-packages\streamlit\runtime\scriptrunner\exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
  File "D:\Anaconda\envs\videolingo\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 590, in code_to_exec
    exec(code, module.__dict__)
  File "D:\dub\VideoLingo\st.py", line 123, in <module>
    main()
  File "D:\dub\VideoLingo\st.py", line 120, in main
    audio_processing_section()
  File "D:\dub\VideoLingo\st.py", line 79, in audio_processing_section
    process_audio()
  File "D:\dub\VideoLingo\st.py", line 99, in process_audio
    step10_gen_audio.gen_audio()
  File "D:\dub\VideoLingo\core\step10_gen_audio.py", line 207, in gen_audio
    tasks_df = generate_tts_audio(tasks_df)
  File "D:\dub\VideoLingo\core\step10_gen_audio.py", line 99, in generate_tts_audio
    raise e
  File "D:\dub\VideoLingo\core\step10_gen_audio.py", line 94, in generate_tts_audio
    number, real_dur = process_row(row, tasks_df)
  File "D:\dub\VideoLingo\core\step10_gen_audio.py", line 78, in process_row
    tts_main(line, temp_file, number, tasks_df)
  File "D:\dub\VideoLingo\core\all_tts_functions\tts_main.py", line 56, in tts_main
    raise Exception(f"Failed to generate audio after {max_retries} attempts: {str(e)}")
Exception: Failed to generate audio after 3 attempts: Generated audio duration is 0

**Comment by qunyinghuicui-copy** [comment]
![屏幕截图 2024-11-22 215429](https://github.com/user-attachments/assets/5e45c325-5341-44d3-bcf5-c6ce5ece1911)
![屏幕截图 2024-11-22 215434](https://github.com/user-attachments/assets/302c47b5-49b9-4ac7-a143-5afb15c88a20)

**Comment by Huanshere** [comment]
可以先使用 GPT-SoVits 自己的 webUI 看看电脑能否正常使用这个模型推理语音

**Comment by qunyinghuicui-copy** [comment]
> 可以先使用 GPT-SoVits 自己的 webUI 看看电脑能否正常使用这个模型推理语音

能正常推理

**Comment by qunyinghuicui-copy** [comment]
![屏幕截图 2024-11-23 201915](https://github.com/user-attachments/assets/dff50a1d-e29b-4d71-b6b4-4c905efe1849)

**Comment by qunyinghuicui-copy** [comment]
![屏幕截图 2024-11-25 213623](https://github.com/user-attachments/assets/88b9f3c5-5000-4c46-b2d8-055e5d3b721a)
能解决吗，有什么按模式二克隆的声音有点怪

**Comment by Huanshere** [comment]
这些具体的错误似乎和参考音频或者文本有关？我没有深入探讨过单独失败的原因，如果你有时间单独挑出失败的那个然后找到原因，欢迎贡献代码～

**Comment by Huanshere** [comment]
是的最近有不少用户反馈，原因是 gptsovits 对于 refer audio 有一定的要求，比如时长比如 prompt，这个需要详细的优化。。。
