### ISSUE TITLE
[Bug] step8_1的短句子合并貌似造成了tts_tasks.xlsx与trans.srt不匹配的问题

### ISSUE THREAD

**Issue by SethDong** [Huanshere/VideoLingo#288]
**报错日志：**
```

[🎬 Starting] Generating dubbing chunks...
[📊 Processing] Analyzing timing and speed...
[🔍 Analyzing] Calculating subtitle timing and speed...
[✂️ Processing] Processing cutoffs...
[✂️ Processing] Generating cutoff points...
[📝 Reading] Loading transcript file...
[❌ Error] Matching failed at line 3:
Target: '在那期视频中我讲解了变换器但那期视频的音频质量不佳'
Current: '在那期视频中我讲解了变换器'
Traceback (most recent call last):
  File "h:\0-project\VideoLingo\core\step8_2_gen_dub_chunks.py", line 203, in <module>     
    gen_dub_chunks()
  File "h:\0-project\VideoLingo\core\step8_2_gen_dub_chunks.py", line 196, in gen_dub_chunks
    raise ValueError("Matching failed")
ValueError: Matching failed

```

**Comment by SethDong** [comment]
[字幕文件.zip](https://github.com/user-attachments/files/17923917/default.zip)

**Comment by SethDong** [comment]
**### _（句子开始）_似乎作为nan被解析**

BTW, trans.srt 809的_（句子开始）_似乎作为nan被解析，导致estimate_duration.py 68行报类型错误：
```
808
00:47:20,158 --> 00:47:23,861
基本上 这表示我们会在前面添加一个称为 SOS 的特殊标记


809
00:47:23,861 --> 00:47:24,942
（句子开始）


810
00:47:26,806 --> 00:47:31,827
你还应该注意 这两个序列其实
```

目前通过在67行加入强制转换规避了这一问题：
```
if not isinstance(text, str):
            text = str(text)
```
