### ISSUE TITLE
识别字幕报错 TypeError: Client.__init__() got an unexpected keyword argument 'proxies'

### ISSUE THREAD

**Issue by BlueBlue7891** [Huanshere/VideoLingo#293]
你好，我在识别字幕后报错，信息如下：
2024-11-29 06:19:22.611 Uncaught app exception
Traceback (most recent call last):
  File "D:\AI\videoLingo\v-l_env\lib\site-packages\streamlit\runtime\scriptrunner\exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
  File "D:\AI\videoLingo\v-l_env\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 590, in code_to_exec
    exec(code, module.__dict__)
  File "D:\AI\VideoLingo\st.py", line 123, in <module>
    main()
  File "D:\AI\VideoLingo\st.py", line 119, in main
    text_processing_section()
  File "D:\AI\VideoLingo\st.py", line 33, in text_processing_section
    process_text()
  File "D:\AI\VideoLingo\st.py", line 50, in process_text
    step3_2_splitbymeaning.split_sentences_by_meaning()
  File "D:\AI\VideoLingo\core\step3_2_splitbymeaning.py", line 119, in split_sentences_by_meaning
    sentences = parallel_split_sentences(sentences, max_length=load_key("max_split_length"), max_workers=load_key("max_workers"), nlp=nlp, retry_attempt=retry_attempt)
  File "D:\AI\VideoLingo\core\step3_2_splitbymeaning.py", line 101, in parallel_split_sentences
    split_result = future.result()
  File "D:\AI\videoLingo\v-l_env\lib\concurrent\futures\_base.py", line 451, in result
    return self.__get_result()
  File "D:\AI\videoLingo\v-l_env\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "D:\AI\videoLingo\v-l_env\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\AI\VideoLingo\core\step3_2_splitbymeaning.py", line 60, in split_sentence
    response_data = ask_gpt(split_prompt + ' ' * retry_attempt, response_json=True, valid_def=valid_split, log_title='sentence_splitbymeaning')
  File "D:\AI\VideoLingo\core\ask_gpt.py", line 60, in ask_gpt
    client = OpenAI(api_key=api_set["key"], base_url=base_url)
  File "D:\AI\videoLingo\v-l_env\lib\site-packages\openai\_client.py", line 123, in __init__
    super().__init__(
  File "D:\AI\videoLingo\v-l_env\lib\site-packages\openai\_base_client.py", line 847, in __init__
    self._client = http_client or SyncHttpxClientWrapper(
  File "D:\AI\videoLingo\v-l_env\lib\site-packages\openai\_base_client.py", line 745, in __init__
    super().__init__(**kwargs)
TypeError: Client.__init__() got an unexpected keyword argument 'proxies'

**Comment by axh2018** [comment]
你好，请问解决了吗，刚刚碰到一模一样的问题

**Comment by Huanshere** [comment]
54159ac 在新的代码中已经修复，这是 openai 库的版本的问题，不知道为什么，之前还不会出错，今天都出错了。在 openai 论坛也看到了类似的讨论。
