### ISSUE TITLE
docker容器运行报错

### ISSUE THREAD

**Issue by ImJoyed** [Huanshere/VideoLingo#296]
Translate and Generate Subtitles阶段，应该是在句子分割完成之后，报错如下
```
✅ Sentence 793 has been successfully split
┏━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Type     ┃ Sentence                                                          ┃
┡━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ Original │ it says read only local constant cannot be used as an assignment  │
│          │ target it's a little weird expression to understand               │
│ Split    │ it says read only local constant cannot be used as an assignment  │
│          │ target || it's a little weird expression to understand            │
└──────────┴───────────────────────────────────────────────────────────────────┘
✅ All sentences have been successfully split!
2024-11-29 06:37:31.610 Uncaught app exception
Traceback (most recent call last):
  File "/app/core/ask_gpt.py", line 82, in ask_gpt
    raise ValueError(f"❎ API response error: {valid_response['message']}")
ValueError: ❎ API response error: Missing required key: terms

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/core/ask_gpt.py", line 90, in ask_gpt
    raise Exception(f"JSON parsing still failed after {max_retries} attempts: {e}")
Exception: JSON parsing still failed after 3 attempts: ❎ API response error: Missing required key: terms

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
  File "/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py", line 590, in code_to_exec
    exec(code, module.__dict__)
  File "/app/st.py", line 124, in <module>
    main()
  File "/app/st.py", line 120, in main
    text_processing_section()
  File "/app/st.py", line 36, in text_processing_section
    process_text()
  File "/app/st.py", line 56, in process_text
    step4_1_summarize.get_summary()
  File "/app/core/step4_1_summarize.py", line 39, in get_summary
    summary = ask_gpt(summary_prompt, response_json=True, valid_def=valid_summary, log_title='summary')
  File "/app/core/ask_gpt.py", line 103, in ask_gpt
    raise Exception(f"Still failed after {max_retries} attempts: {e}")
Exception: Still failed after 3 attempts: JSON parsing still failed after 3 attempts: ❎ API response error: Missing required key: terms
```

**Comment by ImJoyed** [comment]
LLM模型使用的是ollama运行的qwen2.5:32b

**Comment by Huanshere** [comment]
本地运行请随便填写 apikey，并且注意设置 config 中的并发数量为 1

**Comment by ImJoyed** [comment]
> 本地运行请随便填写 apikey，并且注意设置 config 中的并发数量为 1

应该是summary任务的时候，response返回的不是json格式。可能是因为字幕文本太长或者模型能力不够，没按要求生成json

**Comment by Huanshere** [comment]
嗯是的，本地运行的大模型在面对长文本的时候都会出错。。。
