### ISSUE TITLE
No module named 'demucs.api'的问题

### ISSUE THREAD

**Issue by jadewolf1978** [Huanshere/VideoLingo#307]
INFO:speechbrain.utils.quirks:Applied quirks (see `speechbrain.utils.quirks`): [disable_jit_profiling, allow_tf32]
INFO:speechbrain.utils.quirks:Excluded quirks specified by the `SB_DISABLE_QUIRKS` environment (comma-separated list): []
2024-12-02 17:04:03.072 Uncaught app exception
Traceback (most recent call last):
  File "C:\anaconda3\envs\videolingo\lib\site-packages\streamlit\runtime\scriptrunner\exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
  File "C:\anaconda3\envs\videolingo\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 590, in code_to_exec
    exec(code, module.__dict__)
  File "C:\VideoLingo\st.py", line 3, in <module>
    from st_components.imports_and_utils import *
  File "C:\VideoLingo\st_components\imports_and_utils.py", line 3, in <module>
    from core import (
  File "C:\VideoLingo\core\step2_whisperX.py", line 17, in <module>
    from core.all_whisper_methods.demucs_vl import demucs_main, RAW_AUDIO_FILE, VOCAL_AUDIO_FILE
  File "C:\VideoLingo\core\all_whisper_methods\demucs_vl.py", line 10, in <module>
    from demucs.api import Separator
ModuleNotFoundError: No module named 'demucs.api'

刚全部安装好，启动就有这个错误。demucs也删除再安装了，不知道是啥原因，有人知道么

**Comment by Huanshere** [comment]
现在的安装从 git 安装 没有见到别的用户有报错～

**Comment by chunhuizhang** [comment]
是因为 demucs 源码安装时，它约定了 torchaudio 的版本：torchaudio<2.2,>=0.8

ERROR: Could not find a version that satisfies the requirement torchaudio<2.2,>=0.8 (from demucs) (from versions: 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.3.1, 2.4.0, 2.4.1, 2.5.0, 2.5.1)
ERROR: No matching distribution found for torchaudio<2.2,>=0.8

导致 demucs 源码安装失败
