### ISSUE TITLE
Merging audio segments issues

### ISSUE THREAD

**Issue by coooup** [Huanshere/VideoLingo#315]
After installing and running from source code:
config -->

-302ai
-claude-3-5-sonnet-20240620 or gemini-1.5-pro-002
-Turn off the burn subtitle button
-azure tts

log----->

🔄 Starting audio merge process...
⠋ 🎵 Merging audio segments... ----------------------------------------   0%
2024-12-03 14:40:22.917 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\XXX\.conda\envs\sulingo\lib\site-packages\streamlit\runtime\scriptrunner\exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
  File "C:\Users\XXX\.conda\envs\sulingo\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 590, in code_to_exec
    exec(code, module.__dict__)
  File "C:\Users\XXX\Desktop\VideoLingo\st.py", line 123, in <module>
    main()
  File "C:\Users\XXX\Desktop\VideoLingo\st.py", line 120, in main
    audio_processing_section()
  File "C:\Users\XXX\Desktop\VideoLingo\st.py", line 79, in audio_processing_section
    process_audio()
  File "C:\Users\XXX\Desktop\VideoLingo\st.py", line 101, in process_audio
    step11_merge_full_audio.merge_full_audio()
  File "C:\Users\XXX\Desktop\VideoLingo\core\step11_merge_full_audio.py", line 131, in merge_full_audio
    merged_audio = merge_audio_segments(audios, new_sub_times, sample_rate)
  File "C:\Users\XXX\Desktop\VideoLingo\core\step11_merge_full_audio.py", line 73, in merge_audio_segments
    audio_segment = process_audio_segment(audio_file)
  File "C:\Users\XXX\Desktop\VideoLingo\core\step11_merge_full_audio.py", line 52, in process_audio_segment
    audio_segment = AudioSegment.from_mp3(temp_file)
  File "C:\Users\XXX\.conda\envs\sulingo\lib\site-packages\pydub\audio_segment.py", line 796, in from_mp3
    return cls.from_file(file, 'mp3', parameters=parameters)
  File "C:\Users\XXX\.conda\envs\sulingo\lib\site-packages\pydub\audio_segment.py", line 728, in from_file
    info = mediainfo_json(orig_file, read_ahead_limit=read_ahead_limit)
  File "C:\Users\XXX\.conda\envs\sulingo\lib\site-packages\pydub\utils.py", line 274, in mediainfo_json
    res = Popen(command, stdin=stdin_parameter, stdout=PIPE, stderr=PIPE)
  File "C:\Users\XXX\.conda\envs\sulingo\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\XXX\.conda\envs\sulingo\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2]

**Comment by coooup** [comment]
config-->

-302ai
-claude-3-5-sonnet-20240620 or gemini-1.5-pro-002
-Turn off the burn subtitle button
-azure tts

**Comment by Huanshere** [comment]
Looks like a ffmpeg issue, first check if ffmpeg.exe exists in Videolingo folder (it should be there, just in case).

And according to GPT, `pydub` tried to use `mediainfo` to get the length of an audio file, it suggests downloading [mediainfo](https://mediaarea.net/en/MediaInfo/Download/Windows) and add to sys path (weird solution, I don't have this...). And also check if all audios are generated by tts correctly, which is, check if there's any cli error when generation tts audio.

**Comment by Huanshere** [comment]
Thanks for the solution. I add a hint in Readme about ffmpeg installation right away 52fa5d5 .
