### ISSUE TITLE
重大发现：已经有支持苹果 mps 加速的whisperX

### ISSUE THREAD

**Issue by vanch007** [Huanshere/VideoLingo#323]
https://github.com/m-bain/whisperX/compare/main...NADOOIT:whisperX:feature/macos-support
请求大佬火速更新

**Comment by vanch007** [comment]
是我想的太简单了，whisperX 支持了，但是底层的ctranslate2库还不支持 mps
Traceback (most recent call last):
  File "/opt/miniconda3/envs/videolingo/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
  File "/opt/miniconda3/envs/videolingo/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 590, in code_to_exec
    exec(code, module.__dict__)
  File "/Users/vanch/VideoLingo/st.py", line 123, in <module>
    main()
  File "/Users/vanch/VideoLingo/st.py", line 119, in main
    text_processing_section()
  File "/Users/vanch/VideoLingo/st.py", line 33, in text_processing_section
    process_text()
  File "/Users/vanch/VideoLingo/st.py", line 47, in process_text
    step2_whisperX.transcribe()
  File "/Users/vanch/VideoLingo/core/step2_whisperX.py", line 214, in transcribe
    result = transcribe_audio(whisper_audio, start, end)
  File "/Users/vanch/VideoLingo/core/step2_whisperX.py", line 103, in transcribe_audio
    model = whisperx.load_model(model_name, device, compute_type=compute_type, language=whisper_language, vad_options=vad_options, asr_options=asr_options, download_root=MODEL_DIR)
  File "/opt/miniconda3/envs/videolingo/lib/python3.10/site-packages/whisperx/asr.py", line 288, in load_model
    model = model or WhisperModel(whisper_arch,
  File "/opt/miniconda3/envs/videolingo/lib/python3.10/site-packages/faster_whisper/transcribe.py", line 133, in __init__
    self.model = ctranslate2.models.Whisper(
ValueError: unsupported device mps

**Comment by Huanshere** [comment]
唉 mac 的支持确实比较慢～
