### ISSUE TITLE
youtube下载下来以后生成的是一个mkv，处理字幕时就报错了

### ISSUE THREAD

**Issue by neohob** [Huanshere/VideoLingo#33]
<img width="657" alt="image" src="https://github.com/user-attachments/assets/456bf6f1-8509-4ef5-9e8a-b925f5013d0e">

2024-08-31 23:30:01.615 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\lenovo\anaconda3\envs\videolingo\Lib\site-packages\streamlit\runtime\scriptrunner\exec_code.py", line 85, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "C:\Users\lenovo\anaconda3\envs\videolingo\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 576, in code_to_exec
    exec(code, module.__dict__)
  File "F:\VideoLingo\st.py", line 119, in <module>
    main()
  File "F:\VideoLingo\st.py", line 114, in main
    text_processing_section()
  File "F:\VideoLingo\st.py", line 29, in text_processing_section
    process_text()
  File "F:\VideoLingo\st.py", line 45, in process_text
    video_file = (glob.glob("*.mp4") + glob.glob("*.webm"))[0]
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

**Comment by Huanshere** [comment]
嗯后续会扩展支持... 之前写的时候没考虑到别的格式
