### ISSUE TITLE
SHA256 checksum does not not match

### ISSUE THREAD

**Issue by kernelpod** [Huanshere/VideoLingo#336]
# RuntimeError: Model has been downloaded but the SHA256 checksum does not not match. Please retry loading the model.

`
WhisperX processing error: Model has been downloaded but the SHA256 checksum does not not match. Please retry loading
the model.
2024-12-13 22:10:58.454 Uncaught app exception
Traceback (most recent call last):
  File "D:\Users\tencent\AppData\Local\Programs\Python\Python310\lib\site-packages\streamlit\runtime\scriptrunner\exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
  File "D:\Users\tencent\AppData\Local\Programs\Python\Python310\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 590, in code_to_exec
    exec(code, module.__dict__)
  File "D:\code\projects\VideoLingo\st.py", line 123, in <module>
    main()
  File "D:\code\projects\VideoLingo\st.py", line 119, in main
    text_processing_section()
  File "D:\code\projects\VideoLingo\st.py", line 33, in text_processing_section
    process_text()
  File "D:\code\projects\VideoLingo\st.py", line 47, in process_text
    step2_whisperX.transcribe()
  File "D:\code\projects\VideoLingo\core\step2_whisperX.py", line 184, in transcribe
    result = transcribe_audio(whisper_audio, start, end)
  File "D:\code\projects\VideoLingo\core\step2_whisperX.py", line 90, in transcribe_audio
    model = whisperx.load_model(model_name, device, compute_type=compute_type, language=whisper_language, vad_options=vad_options, asr_options=asr_options, download_root=MODEL_DIR)
  File "D:\Users\tencent\AppData\Local\Programs\Python\Python310\lib\site-packages\whisperx\asr.py", line 347, in load_model
    vad_model = load_vad_model(torch.device(device), use_auth_token=None, **default_vad_options)
  File "D:\Users\tencent\AppData\Local\Programs\Python\Python310\lib\site-packages\whisperx\vad.py", line 47, in load_vad_model
    raise RuntimeError(
RuntimeError: Model has been downloaded but the SHA256 checksum does not not match. Please retry loading the model.
`

**Comment by kernelpod** [comment]
![image](https://github.com/user-attachments/assets/c08215c7-62e2-460c-bb8d-195b975f76ac)

**Comment by Huanshere** [comment]
下载过程网络问题 不是 fasterwhisper 是后续的 vad，需要想办法删除这个 vad 模型然后重新运行
