### ISSUE TITLE
[BUG] “calc_len” 函数返回值类型错误

### ISSUE THREAD

**Issue by yxc0915** [Huanshere/VideoLingo#4]
报错日志如下：
```
2024-08-14 00:14:05.761 Uncaught app exception
Traceback (most recent call last):
  File "D:\Anaconda\envs\videolingo\Lib\site-packages\streamlit\runtime\scriptrunner\exec_code.py", line 85, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "D:\Anaconda\envs\videolingo\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 576, in code_to_exec
    exec(code, module.__dict__)
  File "C:\Users\y2692\Downloads\VideoLingo-main\st.py", line 213, in <module>
    main()
  File "C:\Users\y2692\Downloads\VideoLingo-main\st.py", line 207, in main
    if text_processing_section(progress_bar, step_status, total_steps):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\y2692\Downloads\VideoLingo-main\st.py", line 126, in text_processing_section
    process_text(progress_bar, step_status, total_steps)
  File "C:\Users\y2692\Downloads\VideoLingo-main\st.py", line 149, in process_text
    func()
  File "C:\Users\y2692\Downloads\VideoLingo-main\st.py", line 143, in <lambda>
    ("处理字幕...", lambda: (step5_splitforsub.split_for_sub_main(), step6_generate_final_timeline.align_timestamp_main()), 6),
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\y2692\Downloads\VideoLingo-main\core\step5_splitforsub.py", line 67, in split_for_sub_main
    en_lines, tr_lines = split_align_subs(en_lines, tr_lines, MAX_ENGLISH_LENGTH, MAX_TARGET_LANGUAGE_LENGTH)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\y2692\Downloads\VideoLingo-main\core\step5_splitforsub.py", line 40, in split_align_subs
    if len(en) > max_en_len or calc_len(tr) > max_tr_len:
                               ^^^^^^^^^^^^
  File "C:\Users\y2692\Downloads\VideoLingo-main\core\step5_splitforsub.py", line 16, in calc_len
    return sum(1 if ord(char) > 127 else 0.75 for char in text)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'float' object is not iterable
```

**Comment by Huanshere** [comment]
@33eca63 已修复，问题在于出现了某一行全是数字。在代码处理前增加了强制类型转换。

**Comment by Huanshere** [comment]
@HUANYUXU@33eca63

**Comment by Huanshere** [comment]
@HUANYUXU@33eca63 

已修复，问题在于出现了某一行全是数字。在代码处理前增加了强制类型转换。
