### ISSUE TITLE
[BUG]字幕处理步骤报错："All arrays must be of the same length"

### ISSUE THREAD

**Issue by yxc0915** [Huanshere/VideoLingo#5]
```
================
📄 Original English:    this incredible achievement in brake, technological breakthrough technology, just extraordinary
📚 Split Sentence:  this incredible achievement in brake, [br]  technological breakthrough technology, just extraordinary
🔗 Aligned parts:
SRC_LANG:    ['this incredible achievement in brake,', ' technological breakthrough technology, just extraordinary']
TARGET_LANG: ['售价约200万英镑，', '', '']
================
2024-08-14 09:59:30.452 Uncaught app exception
Traceback (most recent call last):
  File "D:\Anaconda\envs\videolingo\Lib\site-packages\streamlit\runtime\scriptrunner\exec_code.py", line 85, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "D:\Anaconda\envs\videolingo\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 576, in code_to_exec
    exec(code, module.__dict__)
  File "C:\Users\y2692\Downloads\VideoLingo-main\st.py", line 213, in <module>
    main()
  File "C:\Users\y2692\Downloads\VideoLingo-main\st.py", line 207, in main
    if text_processing_section(progress_bar, step_status, total_steps):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\y2692\Downloads\VideoLingo-main\st.py", line 126, in text_processing_section
    process_text(progress_bar, step_status, total_steps)
  File "C:\Users\y2692\Downloads\VideoLingo-main\st.py", line 149, in process_text
    func()
  File "C:\Users\y2692\Downloads\VideoLingo-main\st.py", line 143, in <lambda>
    ("处理字幕...", lambda: (step5_splitforsub.split_for_sub_main(), step6_generate_final_timeline.align_timestamp_main()), 6),
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\y2692\Downloads\VideoLingo-main\core\step5_splitforsub.py", line 72, in split_for_sub_main
    pd.DataFrame({'English': en_lines, 'Translation': tr_lines}).to_excel("output/log/translation_results_for_subtitles.xlsx", index=False)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\envs\videolingo\Lib\site-packages\pandas\core\frame.py", line 778, in __init__
    mgr = dict_to_mgr(data, index, columns, dtype=dtype, copy=copy, typ=manager)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\envs\videolingo\Lib\site-packages\pandas\core\internals\construction.py", line 503, in dict_to_mgr
    return arrays_to_mgr(arrays, columns, index, dtype=dtype, typ=typ, consolidate=copy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\envs\videolingo\Lib\site-packages\pandas\core\internals\construction.py", line 114, in arrays_to_mgr
    index = _extract_index(arrays)
            ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\envs\videolingo\Lib\site-packages\pandas\core\internals\construction.py", line 677, in _extract_index
    raise ValueError("All arrays must be of the same length")
ValueError: All arrays must be of the same length
```

**Comment by Huanshere** [comment]
step5 切割对齐的时候，弱的模型会切出来中文的空行，这样就导致中英文的行数不同无法合并。建议使用sonnet 进行这一步。暂时很难修这个 bug
