### ISSUE TITLE
 module 'subprocess' has no attribute 'CREATE_NEW_CONSOLE' on macos

### ISSUE THREAD

**Issue by colin4k** [Huanshere/VideoLingo#55]
任务 101 处理出错: module 'subprocess' has no attribute 'CREATE_NEW_CONSOLE'                                                                                                                                       │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
100%|###############################################################################################################################################################################| 60/60 [00:00<00:00, 2009.31it/s]

╭────────────────────────────────────────────────────────────────────────────────────────────────── 处理失败的任务 ──────────────────────────────────────────────────────────────────────────────────────────────────╮
│ 以下任务处理出错: 1, 3, 4, 5, 6, 8, 10, 12, 13, 14, 15, 16, 18, 20, 21, 24, 26, 28, 30, 32, 34, 35, 37, 39, 41, 43, 44, 46, 48, 50, 52, 54, 55, 56, 58, 60, 62, 64, 66, 67, 69, 70, 71, 73, 75, 77, 79, 81, 82,    │
│ 83, 85, 87, 89, 90, 92, 93, 95, 97, 100, 101

2024-09-22 10:17:53.230 Uncaught app exception
Traceback (most recent call last):
  File "/Users/colin/opt/anaconda3/envs/videolingo/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/Users/colin/opt/anaconda3/envs/videolingo/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 590, in code_to_exec
    exec(code, module.__dict__)
  File "/Users/colin/workspace/VideoLingo/st.py", line 123, in <module>
    main()
  File "/Users/colin/workspace/VideoLingo/st.py", line 120, in main
    audio_processing_section()
  File "/Users/colin/workspace/VideoLingo/st.py", line 80, in audio_processing_section
    process_audio()
  File "/Users/colin/workspace/VideoLingo/st.py", line 100, in process_audio
    step10_gen_audio.process_sovits_tasks()
  File "/Users/colin/workspace/VideoLingo/core/step10_gen_audio.py", line 118, in process_sovits_tasks
    raise Exception()
Exception

**Comment by Huanshere** [comment]
GPT SoVITS 需要配置好，可以参考本地安装指南下载配置，注意放对文件路径～

**Comment by colin4k** [comment]
> GPT SoVITS 需要配置好，可以参考本地安装指南下载配置，注意放对文件路径～

配置好了的·，手动执行 api-v2.py 可以正常启动 api 服务，查了下应该是macos 不支持subprocess.CREATE_NEW_CONSOLE这个语法

**Comment by Huanshere** [comment]
原来如此!谢谢提醒！我去加上提示

**Comment by Huanshere** [comment]
已在 4e4b46e 中加上了提示，如果是mac系统会提示用户手动启动sovits api服务器，谢谢反馈~
