### ISSUE TITLE
KeyError: 'Original Subtitle'

### ISSUE THREAD

**Issue by colin4k** [Huanshere/VideoLingo#57]
以下错误会随机出现，有时候重新尝试就好了，但是出现的几率很高：

2024-09-22 19:41:32.192 Uncaught app exception
Traceback (most recent call last):
  File "/Users/colin/opt/anaconda3/envs/videolingo/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/Users/colin/opt/anaconda3/envs/videolingo/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 590, in code_to_exec
    exec(code, module.__dict__)
  File "/Users/colin/workspace/VideoLingo/st.py", line 123, in <module>
    main()
  File "/Users/colin/workspace/VideoLingo/st.py", line 119, in main
    text_processing_section()
  File "/Users/colin/workspace/VideoLingo/st.py", line 28, in text_processing_section
    process_text()
  File "/Users/colin/workspace/VideoLingo/st.py", line 56, in process_text
    step4_2_translate_all.translate_all()
  File "/Users/colin/workspace/VideoLingo/core/step4_2_translate_all.py", line 65, in translate_all
    results.append(future.result())
                   ^^^^^^^^^^^^^^^
  File "/Users/colin/opt/anaconda3/envs/videolingo/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/colin/opt/anaconda3/envs/videolingo/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/Users/colin/opt/anaconda3/envs/videolingo/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/colin/workspace/VideoLingo/core/step4_2_translate_all.py", line 40, in translate_chunk
    translation, english_result = translate_lines(chunk, previous_content_prompt, after_content_prompt, things_to_note_prompt, theme_prompt, i)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/colin/workspace/VideoLingo/core/translate_once.py", line 64, in translate_lines
    prompt2 = get_prompt_expressiveness(faith_result, lines, shared_prompt)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/colin/workspace/VideoLingo/core/prompts_storage.py", line 192, in get_prompt_expressiveness
    "Original Subtitle": value['Original Subtitle'],
                         ~~~~~^^^^^^^^^^^^^^^^^^^^^
KeyError: 'Original Subtitle'

**Comment by Huanshere** [comment]
使用的什么llm？什么提供商?如果是较弱的模型或不稳定的提供商有时候会这样

**Comment by colin4k** [comment]
siliconflow的qwen2.5-7b ***@***.*** ***@***.*** ---- 回复的原邮件 ---- 发件人 ***@***.***> 日期 2024年09月22日 23:18 收件人 ***@***.***> 抄送至 ZHU ***@***.***>***@***.***> 主题 Re: [Huanshere/VideoLingo] KeyError: 'Original Subtitle' (Issue #57) 使用的什么llm？什么提供商?如果是较弱的模型或不稳定的提供商有时候会这样 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by colin4k** [comment]
> 使用的什么llm？什么提供商?如果是较弱的模型或不稳定的提供商有时候会这样

用的是 SiliconFlow 的 qwen2.5-7b，速度和稳定性应该没问题，看来是大模型能力的问题，我来试试gpt-o1，另外建议可以增加一个并发率的参数设置功能，这样子就可以尝试一下本地跑的大模型了

**Comment by Huanshere** [comment]
不建议使用7b等小模型，建议72B和sonnet，详见本地安装文档

**Comment by colin4k** [comment]
> 不建议使用7b等小模型，建议72B和sonnet，详见本地安装文档

嗯，换成 gpt-4o-mini 没问题了

**Comment by Huanshere** [comment]
小模型在切割的时候虽然格式正确，但是没法真正做到按照要求来切割，为了最佳效果还是建议用3.5sonnet~

**Comment by colin4k** [comment]
> 小模型在切割的时候虽然格式正确，但是没法真正做到按照要求来切割，为了最佳效果还是建议用3.5sonnet~

现在换成本地跑的 qwen2.5-32b 试试
