### ISSUE TITLE
windows11下，install.py 出错，numpy 降级又升级，一直报错，无法解决

### ISSUE THREAD

**Issue by neohob** [Huanshere/VideoLingo#6]
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.1 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "F:\VideoLingo\install.py", line 265, in <module>
    main()
  File "F:\VideoLingo\install.py", line 242, in main
    download_spacy_model()
  File "F:\VideoLingo\install.py", line 82, in download_spacy_model
    import spacy
  File "C:\Users\lenovo\anaconda3\envs\videolingo\Lib\site-packages\spacy\__init__.py", line 6, in <module>
    from .errors import setup_default_warnings
  File "C:\Users\lenovo\anaconda3\envs\videolingo\Lib\site-packages\spacy\errors.py", line 3, in <module>
    from .compat import Literal
  File "C:\Users\lenovo\anaconda3\envs\videolingo\Lib\site-packages\spacy\compat.py", line 4, in <module>
    from thinc.util import copy_array
  File "C:\Users\lenovo\anaconda3\envs\videolingo\Lib\site-packages\thinc\__init__.py", line 5, in <module>
    from .config import registry
  File "C:\Users\lenovo\anaconda3\envs\videolingo\Lib\site-packages\thinc\config.py", line 5, in <module>
    from .types import Decorator
  File "C:\Users\lenovo\anaconda3\envs\videolingo\Lib\site-packages\thinc\types.py", line 25, in <module>
    from .compat import cupy, has_cupy
  File "C:\Users\lenovo\anaconda3\envs\videolingo\Lib\site-packages\thinc\compat.py", line 32, in <module>
    import torch
  File "C:\Users\lenovo\anaconda3\envs\videolingo\Lib\site-packages\torch\__init__.py", line 2120, in <module>
    from torch._higher_order_ops import cond
  File "C:\Users\lenovo\anaconda3\envs\videolingo\Lib\site-packages\torch\_higher_order_ops\__init__.py", line 1, in <module>
    from .cond import cond
  File "C:\Users\lenovo\anaconda3\envs\videolingo\Lib\site-packages\torch\_higher_order_ops\cond.py", line 5, in <module>
    import torch._subclasses.functional_tensor
  File "C:\Users\lenovo\anaconda3\envs\videolingo\Lib\site-packages\torch\_subclasses\functional_tensor.py", line 42, in <module>
    class FunctionalTensor(torch.Tensor):
  File "C:\Users\lenovo\anaconda3\envs\videolingo\Lib\site-packages\torch\_subclasses\functional_tensor.py", line 258, in FunctionalTensor
    cpu = _conversion_method_template(device=torch.device("cpu"))
C:\Users\lenovo\anaconda3\envs\videolingo\Lib\site-packages\torch\_subclasses\functional_tensor.py:258: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\utils\tensor_numpy.cpp:84.)
  cpu = _conversion_method_template(device=torch.device("cpu"))
Traceback (most recent call last):
  File "F:\VideoLingo\install.py", line 265, in <module>
    main()
  File "F:\VideoLingo\install.py", line 242, in main
    download_spacy_model()
  File "F:\VideoLingo\install.py", line 82, in download_spacy_model
    import spacy
  File "C:\Users\lenovo\anaconda3\envs\videolingo\Lib\site-packages\spacy\__init__.py", line 6, in <module>
    from .errors import setup_default_warnings
  File "C:\Users\lenovo\anaconda3\envs\videolingo\Lib\site-packages\spacy\errors.py", line 3, in <module>
    from .compat import Literal
  File "C:\Users\lenovo\anaconda3\envs\videolingo\Lib\site-packages\spacy\compat.py", line 39, in <module>
    from thinc.api import Optimizer  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lenovo\anaconda3\envs\videolingo\Lib\site-packages\thinc\api.py", line 1, in <module>
    from .backends import (
  File "C:\Users\lenovo\anaconda3\envs\videolingo\Lib\site-packages\thinc\backends\__init__.py", line 17, in <module>
    from .cupy_ops import CupyOps
  File "C:\Users\lenovo\anaconda3\envs\videolingo\Lib\site-packages\thinc\backends\cupy_ops.py", line 16, in <module>
    from .numpy_ops import NumpyOps
  File "thinc\backends\numpy_ops.pyx", line 1, in init thinc.backends.numpy_ops
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

(videolingo) F:\VideoLingo>python
Python 3.12.0 | packaged by Anaconda, Inc. | (main, Oct  2 2023, 17:20:38) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by Huanshere** [comment]
感谢反馈，看起来似乎是 spacy 库的问题，试试单开一个环境运行一个 spacy 的 demo 代码，我回去修一修这个。

本项目刚上传在趋动云，如果实在装不上可以考虑用云平台～

**Comment by neohob** [comment]
驱动云怎么访问你的项目？colab 有可能吗

**Comment by Huanshere** [comment]
趋动云已经上线了，在项目主页介绍中能看到～
win11 的 numpy 版本问题也尝试解决了，在 requirements 中固定了 numpy==1.26.4～ 6a01154
