### ISSUE TITLE
Error： empty translation rows

### ISSUE THREAD

**Issue by 1PercentSync** [Huanshere/VideoLingo#62]
╭────────────────────────────────────────────────────── Warning ───────────────────────────────────────────────────────╮
│ 🚨 File `translation_results.xlsx` already exists, skipping TRANSLATE ALL.                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
🚨 File `translation_results_for_subtitles.xlsx` already exists, skipping this step.
╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ 🚫 Detected empty translation rows! Please manually check the empty rows in `output\log                              │
│ ranslation_results_for_subtitles.xlsx` and fill them with appropriate content, then run again.                       │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
2024-09-23 19:55:21.964 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\Alex\.conda\envs\videolingo\lib\site-packages\streamlit\runtime\scriptrunner\exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
  File "C:\Users\Alex\.conda\envs\videolingo\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 590, in code_to_exec
    exec(code, module.__dict__)
  File "C:\Users\Alex\Documents\GitHub\VideoLingo\st.py", line 128, in <module>
    main()
  File "C:\Users\Alex\Documents\GitHub\VideoLingo\st.py", line 124, in main
    text_processing_section()
  File "C:\Users\Alex\Documents\GitHub\VideoLingo\st.py", line 28, in text_processing_section
    process_text()
  File "C:\Users\Alex\Documents\GitHub\VideoLingo\st.py", line 62, in process_text
    step6_generate_final_timeline.align_timestamp_main()
  File "C:\Users\Alex\Documents\GitHub\VideoLingo\core\step6_generate_final_timeline.py", line 132, in align_timestamp_main
    raise ValueError("Empty translation rows detected")
ValueError: Empty translation rows detected

能否通过适当的重翻或者分割成更小的块翻译自动处理这个问题？

**Comment by 1PercentSync** [comment]
手动查找后发现实际上是某一行只有一个句号导致的

**Comment by Huanshere** [comment]
请问是用的什么 llm 呢？除了 sonnet 似乎都很容易有小问题

**Comment by Huanshere** [comment]
2df9399 不再推荐 Qwen2.5 如果考虑性价比建议 deepseek

**Comment by 1PercentSync** [comment]
> 请问是用的什么 llm 呢？除了 sonnet 似乎都很容易有小问题

deepseek

**Comment by Huanshere** [comment]
啊。那确实，这些小模型偶尔真的会出一些神奇的结果。

**Comment by Huanshere** [comment]
只能手动修改了。还是建议使用sonnet~！

**Comment by 1PercentSync** [comment]
> 只能手动修改了。还是建议使用sonnet~！

可以问一下为什么要求每一行都要有文字吗，如果是对其是否可以忽略纯符号的行？

**Comment by Huanshere** [comment]
因为基本上可以理解为按照长度切割，将长句切成两半，这时候是没有理由出现单独的标点符号的行的，如果出现一定是有问题（基本就是llm太笨了出问题的），也很有可能导致别的错误，所以会要求手动检查修改。
