### ISSUE TITLE
翻译并生成字幕模块报错

### ISSUE THREAD

**Issue by zongsforce** [Huanshere/VideoLingo#70]
不确定是不是跟韩语相关
```
┏━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Language    ┃ Parts                                                                                                            ┃
┡━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ SRC_LANG    │ 진짜사람하나놀리는건탁월하다고생각합니다.하하하님이조롱같은말을좀하신게                                          │
│             │ 몇개있어요.약간상대를기분나쁘게일부러하려는제스처즈를취하셨을때내취향은아닌것같다는생각은했죠.채팅종료까지10분 … │
│ TARGET_LANG │ 我真的觉得他太擅长调侃别人了。                                                                                   │
│             │ 他那种弯曲的样子实在太搞笑了。                                                                                   │
└─────────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```
```python
2024-09-26 15:57:49.406 Uncaught app exception
Traceback (most recent call last):
  File "/Users/tio/miniconda3/envs/videolingo/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
  File "/Users/tio/miniconda3/envs/videolingo/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 590, in code_to_exec
    exec(code, module.__dict__)
  File "/Users/tio/PycharmProjects/VideoLingo/st.py", line 128, in <module>
    main()
  File "/Users/tio/PycharmProjects/VideoLingo/st.py", line 124, in main
    text_processing_section()
  File "/Users/tio/PycharmProjects/VideoLingo/st.py", line 28, in text_processing_section
    process_text()
  File "/Users/tio/PycharmProjects/VideoLingo/st.py", line 61, in process_text
    step5_splitforsub.split_for_sub_main()
  File "/Users/tio/PycharmProjects/VideoLingo/core/step5_splitforsub.py", line 104, in split_for_sub_main
    pd.DataFrame({'Source': src_lines, 'Translation': tr_lines}).to_excel("output/log/translation_results_for_subtitles.xlsx", index=False)
  File "/Users/tio/miniconda3/envs/videolingo/lib/python3.10/site-packages/pandas/core/frame.py", line 778, in __init__
    mgr = dict_to_mgr(data, index, columns, dtype=dtype, copy=copy, typ=manager)
  File "/Users/tio/miniconda3/envs/videolingo/lib/python3.10/site-packages/pandas/core/internals/construction.py", line 503, in dict_to_mgr
    return arrays_to_mgr(arrays, columns, index, dtype=dtype, typ=typ, consolidate=copy)
  File "/Users/tio/miniconda3/envs/videolingo/lib/python3.10/site-packages/pandas/core/internals/construction.py", line 114, in arrays_to_mgr
    index = _extract_index(arrays)
  File "/Users/tio/miniconda3/envs/videolingo/lib/python3.10/site-packages/pandas/core/internals/construction.py", line 677, in _extract_index
    raise ValueError("All arrays must be of the same length")
ValueError: All arrays must be of the same length
```

**Comment by zongsforce** [comment]
输入语言暂不支持韩语

**Comment by Huanshere** [comment]
嗯是的，其他语言的支持会慢慢做~感谢理解
