### ISSUE TITLE
源码安装的时候，运行报错了

### ISSUE THREAD

**Issue by knightgao** [Huanshere/VideoLingo#89]
AttributeError: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.
File "C:\Users\gao\.conda\envs\videolingo\lib\site-packages\streamlit\runtime\scriptrunner\exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
File "C:\Users\gao\.conda\envs\videolingo\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 579, in code_to_exec
    exec(code, module.__dict__)
File "E:\github\VideoLingo\st.py", line 125, in <module>
    main()
File "E:\github\VideoLingo\st.py", line 121, in main
    text_processing_section()
File "E:\github\VideoLingo\st.py", line 28, in text_processing_section
    process_text()
File "E:\github\VideoLingo\st.py", line 50, in process_text
    step2_whisper.transcribe(video_file)
File "E:\github\VideoLingo\core\step2_whisper.py", line 17, in transcribe
    from core.all_whisper_methods.whisperX import transcribe as ts
File "E:\github\VideoLingo\core\all_whisper_methods\whisperX.py", line 3, in <module>
    import whisperx
File "e:\github\videolingo\third_party\whisperx\whisperx\__init__.py", line 1, in <module>
    from .transcribe import load_model
File "e:\github\videolingo\third_party\whisperx\whisperx\transcribe.py", line 10, in <module>
    from .asr import load_model
File "e:\github\videolingo\third_party\whisperx\whisperx\asr.py", line 13, in <module>
    from .vad import load_vad_model, merge_chunks
File "e:\github\videolingo\third_party\whisperx\whisperx\vad.py", line 9, in <module>
    from pyannote.audio import Model
File "C:\Users\gao\.conda\envs\videolingo\lib\site-packages\pyannote\audio\__init__.py", line 29, in <module>
    from .core.inference import Inference
File "C:\Users\gao\.conda\envs\videolingo\lib\site-packages\pyannote\audio\core\inference.py", line 49, in <module>
    class Inference(BaseInference):
File "C:\Users\gao\.conda\envs\videolingo\lib\site-packages\pyannote\audio\core\inference.py", line 533, in Inference
    missing: float = np.NaN,
File "C:\Users\gao\.conda\envs\videolingo\lib\site-packages\numpy\__init__.py", line 411, in __getattr__
    raise AttributeError(

**Comment by Huanshere** [comment]
请问是 mac 系统吗？确实还没有在 mac 上测试运行过本地部署的 whisperX，我待会试试

**Comment by Huanshere** [comment]
在 43a8142 中已固定版本，请更换到 numpy 1.26.4

**Comment by lemonadetime** [comment]
> core

你是我的神！

**Comment by foxleeda** [comment]
> core/_11_merge_audio.py 报错 需要添加 import numpy as np导入 numpy 库并将其命名为 np
> 
> 报错内容： `🎬 Starting audio merging process... ────────────────────────── Traceback (most recent call last) ─────────────────────────── D:.conda\envs\videolingo\lib\site-packages\streamlit\runtime\scriptrunner\exec_code .py:128 in exec_func_with_error_handling
> 
> D:.conda\envs\videolingo\lib\site-packages\streamlit\runtime\scriptrunner\script_ru nner.py:669 in code_to_exec
> 
> I:\AI\VideoLingo\st.py:124 in
> 
> code Code download content_copy expand_less 121 │ audio_processing_section() 122 123 if **name** == "**main**":
> 
> ❱ 124 │ main() 125
> 
> I:\AI\VideoLingo\st.py:121 in main
> 
> code Code download content_copy expand_less 118 │ │ st.markdown(give_star_button, unsafe_allow_html=True) 119 │ download_video_section() 120 │ text_processing_section()
> 
> ❱ 121 │ audio_processing_section() 122 123 if name == "main": 124 │ main()
> 
> I:\AI\VideoLingo\st.py:79 in audio_processing_section
> 
> code Code download content_copy expand_less 76 │ │ """, unsafe_allow_html=True) 77 │ │ if not os.path.exists(DUB_VIDEO): 78 │ │ │ if st.button(t("Start Audio Processing"), key="audio_processing_bu
> 
> ❱ 79 │ │ │ │ process_audio() 80 │ │ │ │ st.rerun() 81 │ │ else: 82 │ │ │ st.success(t("Audio processing is complete! You can check the audi
> 
> I:\AI\VideoLingo\st.py:101 in process_audio
> 
> code Code download content_copy expand_less 98 │ with st.spinner(t("Generate all audio")): 99 │ │ _10_gen_audio.gen_audio() 100 │ with st.spinner(t("Merge full audio")):
> 
> ❱ 101 │ │ _11_merge_audio.merge_full_audio() 102 │ with st.spinner(t("Merge dubbing to the video")): 103 │ │ _12_dub_to_vid.merge_video_audio() 104
> 
> I:\AI\VideoLingo\core_11_merge_audio.py:104 in merge_full_audio
> 
> code Code download content_copy expand_less 101 │ console.print("\n[bold cyan]🎬 Starting audio merging process...[/bold cya 102 │ 103 │ with console.status("[bold cyan]📊 Loading data from Excel...[/bold cyan]"
> 
> ❱ 104 │ │ df, lines, new_sub_times = load_and_flatten_data(_8_1_AUDIO_TASK) 105 │ console.print("[bold green]✅ Data loaded successfully[/bold green]") 106 │ 107 │ with console.status("[bold cyan]🔍 Getting audio file list...[/bold cyan]"
> 
> I:\AI\VideoLingo\core_11_merge_audio.py:22 in load_and_flatten_data
> 
> code Code download content_copy expand_less 19 │ lines = [eval(line) if isinstance(line, str) else line for line in df['lin 20 │ lines = [item for sublist in lines for item in sublist] 21 │
> 
> ❱ 22 │ new_sub_times = [eval(time) if isinstance(time, str) else time for time in 23 │ new_sub_times = [item for sublist in new_sub_times for item in sublist] 24 │ 25 │ return df, lines, new_sub_times
> 
> I:\AI\VideoLingo\core_11_merge_audio.py:22 in
> 
> code Code download content_copy expand_less 19 │ lines = [eval(line) if isinstance(line, str) else line for line in df['lin 20 │ lines = [item for sublist in lines for item in sublist] 21 │
> 
> ❱ 22 │ new_sub_times = [eval(time) if isinstance(time, str) else time for time in 23 │ new_sub_times = [item for sublist in new_sub_times for item in sublist] 24 │ 25 │ return df, lines, new_sub_times in :1 ──────────────────────────────────────────────────────────────────────────────────────── NameError: name 'np' is not defined D:.conda\envs\videolingo\lib\site-packages\streamlit\watcher\local_sources_watcher.py:255: UserWarning: Torchaudio's I/O functions now support per-call backend dispatch. Importing backend implementation directly is no longer guaranteed to work. Please use backend keyword with load/save/info function, instead of calling the underlying implementation directly. if hasattr(m, "path")

You save my ass, man!
