### ISSUE TITLE
源码运行Numpy报错

### ISSUE THREAD

**Issue by Rakshesha2024** [Huanshere/VideoLingo#91]
WhisperX model loading error:Numpy is not available
Make sure you have downloaded the model first.
WhisperX processing error: Numpy is not available
2024-10-02 15:36:58.586 Uncaught app exception
Traceback (most recent call last):
  File "D:\anaconda3\envs\videolingo\lib\site-packages\streamlit\runtime\scriptrunner\exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
  File "D:\anaconda3\envs\videolingo\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 579, in code_to_exec
    exec(code, module.__dict__)
  File "D:\AIGC\VideoLingo\st.py", line 125, in <module>
    main()
  File "D:\AIGC\VideoLingo\st.py", line 121, in main
    text_processing_section()
  File "D:\AIGC\VideoLingo\st.py", line 28, in text_processing_section
    process_text()
  File "D:\AIGC\VideoLingo\st.py", line 50, in process_text
    step2_whisper.transcribe(video_file)
  File "D:\AIGC\VideoLingo\core\step2_whisper.py", line 20, in transcribe
    ts(video_file)
  File "D:\AIGC\VideoLingo\core\all_whisper_methods\whisperX.py", line 124, in transcribe
    result = transcribe_audio(audio_file, start, end)
  File "D:\AIGC\VideoLingo\core\all_whisper_methods\whisperX.py", line 45, in transcribe_audio
    model = whisperx.load_model(model_name, device, compute_type=compute_type, download_root=whisperx_model_dir)
  File "d:\aigc\videolingo\third_party\whisperx\whisperx\asr.py", line 347, in load_model
    vad_model = load_vad_model(torch.device(device), use_auth_token=None, **default_vad_options)
  File "d:\aigc\videolingo\third_party\whisperx\whisperx\vad.py", line 51, in load_vad_model
    vad_model = Model.from_pretrained(model_fp, use_auth_token=use_auth_token)
  File "D:\anaconda3\envs\videolingo\lib\site-packages\pyannote\audio\core\model.py", line 720, in from_pretrained
    raise e
  File "D:\anaconda3\envs\videolingo\lib\site-packages\pyannote\audio\core\model.py", line 696, in from_pretrained
    model = Klass.load_from_checkpoint(
  File "D:\anaconda3\envs\videolingo\lib\site-packages\pytorch_lightning\utilities\model_helpers.py", line 125, in wrapper
    return self.method(cls, *args, **kwargs)
  File "D:\anaconda3\envs\videolingo\lib\site-packages\pytorch_lightning\core\module.py", line 1586, in load_from_checkpoint
    loaded = _load_from_checkpoint(
  File "D:\anaconda3\envs\videolingo\lib\site-packages\pytorch_lightning\core\saving.py", line 91, in _load_from_checkpoint
    model = _load_state(cls, checkpoint, strict=strict, **kwargs)
  File "D:\anaconda3\envs\videolingo\lib\site-packages\pytorch_lightning\core\saving.py", line 165, in _load_state
    obj = instantiator(cls, _cls_kwargs) if instantiator else cls(**_cls_kwargs)
  File "D:\anaconda3\envs\videolingo\lib\site-packages\pyannote\audio\models\segmentation\PyanNet.py", line 92, in __init__
    self.sincnet = SincNet(**self.hparams.sincnet)
  File "D:\anaconda3\envs\videolingo\lib\site-packages\pyannote\audio\models\blocks\sincnet.py", line 52, in __init__
    ParamSincFB(
  File "D:\anaconda3\envs\videolingo\lib\site-packages\asteroid_filterbanks\param_sinc_fb.py", line 56, in __init__
    self._initialize_filters()
  File "D:\anaconda3\envs\videolingo\lib\site-packages\asteroid_filterbanks\param_sinc_fb.py", line 79, in _initialize_filters
    self.low_hz_ = nn.Parameter(torch.from_numpy(hz[:-1]).view(-1, 1))
RuntimeError: Numpy is not available

Numpy更换过2.0.0和1.26.4版本，都会跳出这个报错

**Comment by Huanshere** [comment]
我使用的是1.26.4，我检查一下其他的依赖，谢谢反馈

**Comment by SomeoneKong** [comment]
2.0似乎是不行的，换成了1.26.4就可以跑了
